### ISSUE TITLE
flesh out default configure options

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#1]
Currently the configure options are:
 * --with-ipv6
 * --with-pcre-jit

As the defaults configure options will be used by everyone who pulls the image from Docker Hub, we should include the most common options, perhaps including ones that have security best practices.

**Comment by FourierTransformer** [comment]
I'm definitely not an nginx guru, but I'd consider:

-     --with-file-aio (for async file serving)
-     --with-md5-asm (for running md5 with "assembler sources")
-     --with-sha1-asm (for running sha1 with "assembler sources")

Note: I'm not sure if the md5/sha1 asm will work on all dockerable cpu architectures or not...

If you want http2/ssl option by default:

-     --with-http_ssl_module
-     --with-http_v2_module

Other ones that could potentially be useful (these assume that people will only use lua, so it might not be the best option if you're trying to stay super flexible as they disable cgi/wsgi scripting capabilities):

-     --without-http_fastcgi_module
-     --without-http_uwsgi_module
-     --without-http_scgi_module

Digital Ocean lays out some nice options (https://www.digitalocean.com/community/tutorials/how-to-compile-nginx-from-source-on-a-centos-6-4-x64-vps) and explains them fairly well!
