### ISSUE TITLE
Update RESTY_OPENSSL_VERSION to 1.0.2h

### ISSUE THREAD

**Issue by gastounage** [openresty/docker-openresty#10]
Hi,

openssl 1.0.2e sources seems to be unavailable, causing recents build dockerhub build failures: https://hub.docker.com/r/openresty/openresty/builds/

RESTY_OPENSSL_VERSION should be upgraded to 1.0.2h

-- 
Alex.

**Comment by neomantra** [comment]
Thanks for the heads up!
