### ISSUE TITLE
alpine-fat: use smaller archive for luarocks

### ISSUE THREAD

**Issue by akornatskyy** [openresty/docker-openresty#100]
Consider to use luarocks archive from https://luarocks.github.io/luarocks/releases/.

Just to compare download size:

```
5.2M  luarocks-3.0.4.tar.gz
5.2M  luarocks-3.1.2.tar.gz
```
vs

```
201K luarocks-3.0.4.tar.gz
212K luarocks-3.1.2.tar.gz
```

**Comment by neomantra** [comment]
That's really interesting, thanks for catching that.  Apparently, the GitHub releases page has `win32` files in it but the `github.io` URL doesn't.  I'll bundle this work with upgrading to luarocks 3.1.2.

**Comment by neomantra** [comment]
This new URL is on `1.15.8.1rc2-1` along with LuaRocks 3.1.2
