### ISSUE TITLE
upgrade to OpenSSL 1.1.1

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#101]
Once upstream upgrades to OpenSSL 1.1.1, we will upgrade the Docker images. (#100)

Once this happens, we can bump Alpine to 3.9 (#94)

**Comment by thibaultcha** [comment]
Hi @neomantra!

Support for OpenSSL 1.1.1 in `ssl_session_fetch_by_lua*` has now landed in lua-nginx-module (see my comment here: https://github.com/openresty/openresty/issues/456) :)

**Comment by neomantra** [comment]
The image tagged `1.15.8.1-2-alpine` uses Alpine 3.9 with OpenSSL 1.1.1c
