### ISSUE TITLE
Add `nosse42` images

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#103]
By default, OpenResty builds with SSE 4.2 optimizations enabled.  Platforms which don't support SSE 4.2 need an image without that enabled.   Add these as flavors to the automated build.

One motivation for this (versus forcing these subset of users to build their own) is that the non-SSE platforms are often embedded systems on which build might be a pain.   Plus, why should they learn about building images and nuances when they just want an app server on their NAS...

So if Travis can support this easily, let's add it.

**Comment by neomantra** [comment]
@torarnv can you try the following image tags and see if they run on your NAS without segfault?  I don't have a non-SSE-4.2 system...

* openresty/openresty:1.15.8.1rc2-2-bionic-nosse42-temp 
* openresty/openresty:1.15.8.1rc2-2-alpine-nosse42-temp 
* openresty/openresty:1.15.8.1rc2-2-alpine-fat-nosse42-temp 

If they work, then I'll put this tooling on Travis and formally release them (and will delete those `-temp` tags).

**Comment by torarnv** [comment]
Seems to work! Only tried the bionic one, but whereas `docker run -it openresty/openresty:stretch  openresty -v`gives an exit code of 132, `docker run -it openresty/openresty:1.15.8.1rc2-2-bionic-nosse42-temp openresty -v` outputs `nginx version: openresty/1.15.8.1rc2`

**Comment by neomantra** [comment]
I force-pushed an update commit because of a bad commit message.  Generally a no-no but don't expect anybody to have cloned the repo in the last 8 minutes.  Hopefully I'm not proven wrong.

**Comment by neomantra** [comment]
These are tagged:
 * bionic-nosse42
 * xenial-nosse42
 * alpine-fat-nosse42
 * alpine-nosse42

I'm waiting for any other news before tagging an RC.

**Comment by torarnv** [comment]
Thanks @neomantra !!

**Comment by yangzhaofeng** [comment]
Can you please add buster-nosse42 or disco-nosse42? Some packages (like libcjson1) are not available in older ubuntu versions. 
BTW, I tried to build buster-nosse42 by myself with `--build-arg RESTY_LUAJIT_OPTIONS="--with-luajit-xcflags='-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -mno-sse4.2'"` before but still built a sse42 version.

**Comment by neomantra** [comment]
@yangzhaofeng I added a `buster-nosse42` version to the travis build.  

You'll be able to try out `openresty/openresty:buster-nosse42` once it is done ([check here](https://travis-ci.org/openresty/docker-openresty)).   Let me know if it works for you as I don't have a non-sse4.2 system.  It does the same build-arg you show above -- I'm not sure why it didn't work for you, but it seemed like it worked on other distros for other users. 

I'm not going to release any `disco` images, but I will release an `focal` flavor once Ubuntu releases 20.04 in April.

**Comment by yangzhaofeng** [comment]
@neomantra Currently the device is not available, for we are starting our lunar new year holiday today and will come back to company two weeks later. I will test the two images as soon as possible after I return.

Currently I was using a workaround running openresty (alpine-fat-nosse42) and other programs in different docker containers (the other in debian:buster) and communicate with exec.sock in the same docker volume.

**Comment by neomantra** [comment]
There are now also `focal-nosse42` images.
https://hub.docker.com/r/openresty/openresty/tags?page=1&name=focal
