### ISSUE TITLE
Create version 1.15.8.1

### ISSUE THREAD

**Issue by JorritSalverda** [openresty/docker-openresty#105]
Version 1.15.8.1 has been released recently, see https://openresty.org/en/ann-1015008001.html. Unfortunately I don't see new tags at https://hub.docker.com/r/openresty/openresty after the release candidates. Hopefully you can soon create this new version in all flavours.

**Comment by neomantra** [comment]
Thanks for the heads up, I didn’t see it. It will be tagged soon.

**Comment by JorritSalverda** [comment]
Awesome, I see them now!
