### ISSUE TITLE
add pcre build support for alpine & alpine-fat

### ISSUE THREAD

**Issue by chrisLeeTW** [openresty/docker-openresty#108]
Hello,

I've faced the same problem for this issue (https://github.com/openresty/lua-resty-core/issues/258) with alpine & alpine-fat.

It's looks like there no pcre support during the compilation. 

May I know that is intended behavior or just some thing missing before ?

Thanks.

**Comment by neomantra** [comment]
We install PCRE ourselves as is needed for the OpenResty build, but maybe we need to do what [agentzh refers to here](https://github.com/openresty/lua-resty-core/issues/258#issuecomment-494912882).  I will research it further.

**Comment by vkill** [comment]
+1

**Comment by neomantra** [comment]
@vkill Thanks for the PR.  There's also the Nginx compile lines in that link I have above... I'll pow wow with the OpenResty packagers this week to nail down the exact incantations needed.  

I'm worried that what you have in the PR fixes one thing but doesn't fix others.  But I also wonder if your PR also fixes #22, which would be great. 

I also want to fix all the build-from-source images in one swoop, so will expand it to that.

**Comment by vkill** [comment]
Hi @neomantra , #22 was fixed. the `--enable-unicode-properties` option make it effective.

The nginx.conf
```
worker_processes  1;

events {
    worker_connections 4;
}

http {
    server {
        listen 81;

        location /re {
            content_by_lua_block {
                local ngx_re = require "ngx.re"

                local res, err = ngx_re.split("a,b,c,d", ",")
                if err then
                    ngx.log(ngx.ERR, "failed: ", err)
                    return
                end

                for i = 1, #res do
                    ngx.say(res[i])
                end

local newstr, n, err = ngx.re.gsub("测 试 用 例", "[ \t]", "", "ju")
ngx.say(newstr)
            }
        }
    }
}
```

The result:
```
a
b
c
d
测试用例
```

**Comment by neomantra** [comment]
@vkill @chrisLeeTW  I've just pushed a modified version of the #113 pull request.   Please check it out and let me know if it works for you.    I'm adding one more change to this release and then will tag it.  Thanks for the testing and the direction for fixing this issue.

@vkill I'm going to close your PR once this is released but if you want to be in the AUTHORS file, give me the name+email you want in there (or no email is fine too).

**Comment by vkill** [comment]
@neomantra It works for me, and I was built the new image for [apisix](/iresty/docker-apisix/pull/1), it also works.

**Comment by neomantra** [comment]
Great, I just tagged `1.15.8.1-3` with this.   Thanks again for the help.
