### ISSUE TITLE
Adding ngx_cache_purge module

### ISSUE THREAD

**Issue by skhattane** [openresty/docker-openresty#110]
Hi guys,

I need to add the nginx_cache_module (for cache invalidation) to openresty.
I try to build it from source as mentioned in the README with the "RESTY_CONFIG_OPTIONS_MORE" argument.

Here is my command : 
`docker build --build-arg RESTY_CONFIG_OPTIONS_MORE=--add-module=../extension/ngx_cache_purge-2.3 -t openresty -f xenial/Dockerfile .`

Here is the error
```
./configure: error: no ../extension/ngx_cache_purge-2.3/config was found
ERROR: failed to run command: sh ./configure --prefix=/usr/local/openresty/nginx \...
```
There is a config file in the extension folder.
Any ideas ?

I downloaded the extension from http://labs.frickle.com/files/

**Comment by neomantra** [comment]
You need to get those `ngx_cache_purge` files into the build environment in order for the build steps to see them.  They are on your host but not in Docker.

One way is to modify the Dockerfile and use an `ADD` stanza...

Or you can download it (e.g. using `curl`) as a `RESTY_EVAL_PRE_CONFIGURE` step.

**Comment by agentzh** [comment]
The cache purge module is no longer maintained. We surely won't want to include it in our official images by default.

**Comment by neomantra** [comment]
I wasn't considering adding it to the official image.  Also, I'm going to seek more parity with the upstream builds via #109 

But, the images do give customization options for people to do whatever they want.. and it is these image build options (for their own builds, not our official Travis) which give a lot of flexibility.  They should be able to get it to work -- assuming the module itself isn't broken.

**Comment by neomantra** [comment]
Closing this as we aren't adding it and you haven't asked for more help.  Feel free to re-open if you make progress and have still have questions on how to include it in your own builds.

**Comment by adityapatadia** [comment]
@agentzh this module is now nicely maintained. It would make sense to add this: https://github.com/torden/ngx_cache_purge

**Comment by agentzh** [comment]
@adityapatadia We generally don't add modules that we haven't tested the compatibility ourselves. Unless you can guarentee it is fully supported in our test matrix: http://qa.openresty.org/
