### ISSUE TITLE
System crash during build

### ISSUE THREAD

**Issue by adahlmanpinterest** [openresty/docker-openresty#111]
Currently using [alpine/openresty](https://github.com/openresty/docker-openresty/blob/master/alpine/Dockerfile).  When trying to build the image I'm seeing this for about 1000 lines and then the host stops responding as it looks like Docker crashes. 

`gcc  -I. -Icrypto/include -Iinclude -fPIC -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/tmp/openssl-1.1.1c/.openssl/ssl\"" -DENGINESDIR="\"/tmp/openssl-1.1.1c/.openssl/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/ui/ui_openssl.d.tmp -MT crypto/ui/ui_openssl.o -c -o crypto/ui/ui_openssl.o crypto/ui/ui_openssl.c`

Host: 
Ubuntu 18.04
Docker 
  `Client:
   Version:           18.09.6
   API version:       1.39
   Go version:        go1.10.8
   Git commit:        481bc77
   Built:             Sat May  4 02:35:57 2019
   OS/Arch:           linux/amd64
   Experimental:      false

   Server: Docker Engine - Community
   Engine:
   Version:          18.09.6
   API version:      1.39 (minimum version 1.12)
   Go version:       go1.10.8
   Git commit:       481bc77
   Built:            Sat May  4 01:59:36 2019
   OS/Arch:          linux/amd64
  Experimental:     false`

Any ideas?

**Comment by neomantra** [comment]
Hello, sorry for the delay in getting to this.  I just built fine on a Bionic box.  

 * Are you running into disk space or memory issues? 

 * You say "Docker crashes"... can you show the specific error you are talking about?

 * Is your build machine older?  There might be issues with expected instructions on the CPU?

**Comment by adahlmanpinterest** [comment]
This seemed to have been connected to an outdated docker version and low power on the EC2.
