### ISSUE TITLE
Configuration fails alpine-fat

### ISSUE THREAD

**Issue by adahlmanpinterest** [openresty/docker-openresty#116]
I'm trying to get xslt stylesheets to work, however when using the flag 

`--with-http_xslt_module=dynamic` during the configure run I get this error:

```
    && ./configure --with-http_xslt_module=dynamic \
        --prefix=/usr/local/openresty/luajit \
        --with-lua=/usr/local/openresty/luajit \
        --lua-suffix=jit-2.1.0-beta3 \
        --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1 \
Error: Unknown flag: --with-http_xslt_module=dynamic

configure failed.
```

Following the docs in nginx and openresty.

**Comment by neomantra** [comment]
Can you paste more context or link a gist of your Dockerfile?

Note that that flag currently exists in build-from-source images like `alpine`, although I was going to remove it as part of #109.   (I'll give people notice before I actually remove anything).

Also, the recent addition of #114 will allow building dynamic modules separate from the main OpenResty build process.

**Comment by adahlmanpinterest** [comment]
Sure, sorry about the lack of info. Here is the gist of the modified Alpine. 

https://gist.github.com/adahlmanpinterest/b59b774dafc5d174be8ffafbd1dbaff0

I switched off the fat after reading your comment. The issue is that now I'm still getting an error, this time during run, `[emerg] 1#1: unknown directive "xslt_stylesheet" in /usr/local/openresty/nginx/conf/nginx.conf:30
nginx: [emerg] unknown directive "xslt_stylesheet" in /usr/local/openresty/nginx/conf/nginx.conf:30`

My guess this is tied to the xslt module we are trying to use for our stylesheet.

**Comment by neomantra** [comment]
From that gist, I see that you were putting the `--with-http_xslt_module=dynamic` in the PCRE `configure` section, not the OpenResty/Nginx `configure` section.   Hence your original error.

I'm not familiar with that `xslt` module and it's hard to know without seeing your `nginx.conf` file, but make sure you have it in a `location` block as that's the only place it can be ([docs](http://nginx.org/en/docs/http/ngx_http_xslt_module.html#xslt_stylesheet)).

**Comment by neomantra** [comment]
Closing from lack of activity -- feel free to re-open if you still have issues.
