### ISSUE TITLE
Build fails for Xenial

### ISSUE THREAD

**Issue by mbtamuli** [openresty/docker-openresty#117]
### Steps taken

1. Checking out tag `1.15.8.1-3`

2. Ran the following command
```
docker build --build-arg RESTY_J=4 -t myopenresty -f xenial/Dockerfile .
```

### Expected results

[Building (from source)](https://github.com/openresty/docker-openresty#building-from-source) works without modification.

### Actual results

The build fails. Here are the logs: https://paste.ubuntu.com/p/vJ7ZyPsMzD/.

I see this error in line number 4597.
```
mv: cannot stat 'Makefile.new': No such file or directory
```

### Note
1. I tried with two tags - `1.15.8.1-3` and `1.15.8.1-0`.
2. I can see another issue https://github.com/openresty/docker-openresty/issues/102, but it was related to build-args and Docker version. Unrelated.

**Comment by neomantra** [comment]
I think there might be an upstream build concurrency issue?   

Can you try with `--build-arg RESTY_J=1` ?

**Comment by neomantra** [comment]
Yeah, I think it is with OpenSSL: https://github.com/openssl/openssl/issues/7679

**Comment by neomantra** [comment]
And hmm... OpenResty has the patch... 
https://github.com/openresty/openresty/commit/ed328977028c3ec3033bc25873ee360056e247cd

**Comment by mbtamuli** [comment]
> Can you try with --build-arg RESTY_J=1 ?

I'll try this, till the patch makes it into the Docker build.(is this different from the Openresty source?)

**Comment by neomantra** [comment]
The Docker tooling needs to take that patch and apply it and build OpenSSL itself.   So we should be able to fix it in this repo.  I won’t have cycles to do it for a bit
