### ISSUE TITLE
How to set the time zone

### ISSUE THREAD

**Issue by 515445681** [openresty/docker-openresty#129]
How to set the time zone?

**Comment by neomantra** [comment]
I'm not sure if there's a way within OpenResty,  but I do something like this in some of my private images to hardcode a timezone in my image:

```
# Setup New York timezone
# Ubuntu 16.04 tzdata bug:
#   https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata
```

That is static though.  Some of the techniques in this [ServerFault page](https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes) discuss setting it with the `TZ` environment variable upon container run.

**Comment by 515445681** [comment]
I found a solutions.
When use docker-compose,can:

set env TZ.

```
   environment:
       - TZ=Asia/Shanghai
```

When use docker,can:

command -e 

```
docker run -e TZ=Asia/Shanghai
```
