### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by JirkaChadima** [openresty/docker-openresty#130]
It is no longer true that [docker hub does not support ARM builds](https://www.docker.com/blog/docker-official-images-now-multi-platform/). Would it be possible to adjust the build pipeline to `docker push` the ARM-based images as well?

**Comment by neomantra** [comment]
Thanks for pointing that out.  I do note most of that is about the Docker Registry supporting multi-architecture, not necessarily building them.   I see some discussion of how to do it, as well as [recent issues](https://github.com/docker/hub-feedback/issues/1874) describing what a pain it is.    I haven't looked too deep, but if [AppVeyor](https://www.appveyor.com/) makes it easy, that's an option too.

In the OpenResty realm,  it looks like OpenResty upstream supports pre-built arm packages for CentOS....  so that's the only upstream flavor to do.  Then also maybe build-to-source `alpine` and `bionic` flavors.   It looks like you are seeking `alpine` for your project?  

Another complication... there are multiple arm architectures (`arm32v7`, `arm64v8`)..... are they all equally important?  Which do you need?

BTW, I'm a 3D printing enthusiast/maker/artist.

**Comment by JirkaChadima** [comment]
I am looking for `arm32v7`, namely Raspberry Pi support, ideally in an `alpine-fat` flavour with lua support. I know it's kind of specific :-)

Right now, we are building openresty for amd64/armv7 ourselves on Travis in https://github.com/fragaria/python-openresty (see [this script](https://github.com/fragaria/python-openresty/blob/master/build-images.sh) for the workaround for multi-arch build and docker push on travis). It works, but it's painfully slow.

Travis will support multiple architectures eventually as well: https://docs.travis-ci.com/user/multi-cpu-architectures/ - so when they roll out this feature at scale, it might be a good opportunity to consider proper multi-arch builds here.

This is not a real blocker for us, but it would be nice to have everything in one place.

> BTW, I'm a 3D printing enthusiast/maker/artist.

Glad to hear!

**Comment by neomantra** [comment]
Oh actually, I completely blanked that we actually use Travis for image builds, not Docker Hub.   Docker Hub only hosts the images in their Registry.   Those links help a lot, thank you.

So by "painfully slow", do you mean so slow that the builds timeout?   At least our images don't change very often so the time doesn't matter too much (as long as the build succeeds).  Then you can use them as a base image and put whatever you want on top.

**Comment by JirkaChadima** [comment]
That's what we ended up with, we are having a base image with both python and openresty which got built a few times and haven't changed for weeks now. And that works well.

I think Travis has a limit of 50 minutes for a build. [We are just around 40 minutes](https://travis-ci.com/fragaria/python-openresty/builds) here, and if my memory serves me right, when the builds were running, the `amd64` (native arch of Travis) took about 10 minutes and the rest was the virtualized `armv7`. The debugging when the build takes tens of minutes is awfully boring though... 

A big time improvement should be the multi-arch feature of Travis, but then the docker tagging would need to be run in another job when all architectures are done building and pushed to docker.

I can try to take a stab at an experimental `alpine` based build on travis from the current dockerfile just to see if it even fits the time limit.

**Comment by neomantra** [comment]
If you submit a PR that does an `alpine` multi-arch build and it doesn't negatively affect the overall build (e.g. by timing out) and the non-ARM images, I'm happy to review and integrate it into these "official" OpenResty builds.

Hopefully anything architecture-specific in the Dockerfiles can be handled with build `ARGS`.

And once we have that working well, we can expand it to the other flavors as needed

**Comment by JirkaChadima** [comment]
Alright, I'll see what I can do

**Comment by JirkaChadima** [comment]
Unfortnuately, I wasn't successful with the `buildctl` approach, the builds are failing. I'm not sure what's not working :/ If I find some free time, I'll investigate more, but for now, this is up for grabs.

**Comment by neomantra** [comment]
Some related PR work: #157

**Comment by neomantra** [comment]
Starting at `1.17.8.2-3`, ARM builds have landed for `alpine` and `alpine-fat` flavors!  Thanks to @duncaan for spearheading this.

You can either pull the multi-architecture images:
 * `openresty/openresty:1.17.8.2-3-alpine`
 * `openresty/openresty:1.17.8.2-3-alpine-fat`

Or you can pull the architecture-specific image:
 * `openresty/openresty:1.17.8.2-3-alpine-arm64v8`
 * `openresty/openresty:1.17.8.2-3-alpine-fat-arm64v8`
 * `openresty/openresty:1.17.8.2-3-alpine-amd64`
 * `openresty/openresty:1.17.8.2-3-alpine-fat-amd64`

Please test and report any issues! 

Soon we'll have the Ubuntu build-from-source going.  Once OpenResty upstream arm packages exist, we'll provide those as well.

**Comment by neomantra** [comment]
We are now building mutli-architecture ARM/amd64 images from upstream  `centos` and `alpine` packages.
