### ISSUE TITLE
Query on Content-Length response header

### ISSUE THREAD

**Issue by SudharsanN** [openresty/docker-openresty#131]
Hi,
We recently deployed a node app in production that talks to a API endpoint over https. Of late, we started noticing that the call to the API was failing with error as 'Parser Error : Duplicate Content-Length'  and there were a minimum of 6-7 occurrences daily. Though the error message clearly indicates that the API is sending multiple content-length header in the response, we couldn't log these headers in the node app as the call were failing in the underlying node module before reaching our code. 
Below are the open issues related to this in nodejs GitHub page.
https://github.com/nodejs/http-parser/issues/435
https://github.com/nodejs/http-parser/pull/460

In order to troubleshoot the issue better, we decided to introduce a nginx proxy between the node app and the API endpoint. We decided to use OpenResty as it allows us to use lua language and provides the ability to log the entire request and response including the headers in JSON format. Once we capture the error condition, we were planning to share it with the API team and press them for a fix.

To our surprise the error that used to occur at least 6-7 times a day stopped altogether. The log entries were all clean with only one content-length header and no failures in the app as such.
We are pretty sure that the API team didn't fix their code as they are waiting on us to capture the error scenario.

My queries here are as below.
1. Does OpenResty or nginx or luajson that we are using is removing the duplicate content-length header if the values are same ?
2. If the above is true, can you please point me to the docs. Also, is there a way for us to log the headers before it gets removed ?
3. Are we inadvertently removing it as part of the lua script ? We are logging the entire request and response as JSON via this script. Please refer attachment.  

The docker image we are using is "openresty/openresty:jessie" version is 1.13.6.1 and we are using "luajson" package. I have attached the docker file, nginx.conf and lua script as a zip file.
[Archive.zip](https://github.com/openresty/docker-openresty/files/3935842/Archive.zip)

Please clarify at the earliest as we are lost on what exactly is happening here. 

Thanks,
Sudharsan N.

**Comment by neomantra** [comment]
Hello, I can't help with your queries -- you might get more help on the OpenResty mailing list.   But in terms of the OpenResty Docker images, was your OpenResty app working on one image tag and then not on another?

`jessie` images tags shouldn't have changed lately (they were archived a while ago).  But if you move to more recent ones, make sure you use a full tag, like `openresty/openresty:1.15.8.2-5-buster` so you can control versions.

Changes and tags are shown here:
https://github.com/openresty/docker-openresty/blob/master/CHANGELOG.md

**Comment by SudharsanN** [comment]
Thank you for your response.
I will get in touch with openresty mailing list.

Thanks,
Sudharsan N.
