### ISSUE TITLE
Amazon Linux 2 Image

### ISSUE THREAD

**Issue by timoguin** [openresty/docker-openresty#132]
I'd love to see a Docker image added for Amazon Linux 2! Hopefully it shouldn't be much different than the CentOS 7 images.

**Comment by neomantra** [comment]
I just pushed a commit that made this easier... you can run this to build your own image:

```
docker build \
    --build-arg RESTY_IMAGE_BASE=amazonlinux \
    --build-arg RESTY_IMAGE_TAG=2 \
    --build-arg RESTY_YUM_REPO=https://openresty.org/package/amazon/openresty.repo \
    --build-arg RESTY_RPM_DIST="amzn2" \
    -f centos/Dockerfile .
```

Play with that and let me know how it goes.   I'll eventually add it as an actual tagged flavor.

**Comment by neomantra** [comment]
OK, that's on Docker Hub as `openresty/openresty:amzn2`

https://hub.docker.com/layers/openresty/openresty/amzn2/images/sha256-e7f9672e0a2b684d905819294bd35f9075308054adc44b220f64d37a1e9494b4

**Comment by timoguin** [comment]
🎉 Woohoo, thanks! Just now seeing this. I will test it out!
