### ISSUE TITLE
Doc: missing :Z suffix for "docker run"'s  -v DIR:/etc/nginx/conf.d option

### ISSUE THREAD

**Issue by agentzh** [openresty/docker-openresty#134]
According to the manual [here](https://hub.docker.com/r/openresty/openresty/), the following command should do the conf directory mapping:

```bash
docker run -v /my/custom/conf.d:/etc/nginx/conf.d IMAGE
```

But actually this command never works for me on a CentOS 7 host machine since the mapped `/etc/nginx/conf.d` directory lacks permission inside the container:

```shell
$ sudo docker exec -it e8566263466b bash
[root@e8566263466b /]# cd /etc/nginx/conf.d/
[root@e8566263466b conf.d]# ls
ls: cannot open directory .: Permission denied
```

Adding the `:Z` suffix to the `-v` option value fixes the problem:

```bash
sudo docker run -p 8080:80 -v /tmp/vhosts:/etc/nginx/conf.d:Z openresty/openresty:centos-rpm
```

And it seems nginx is doing something similar here as well:

https://github.com/wazuh/wazuh-docker/pull/35/files

**Comment by neomantra** [comment]
Ah, that is due to CentOS using `selinux`:
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

I just added that to the docs, thanks for the report.
