### ISSUE TITLE
Add image for v1.17.8.1

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#138]
The OpenResty v1.17.8.1rc1 upstream series is out...  once there are upstream pre-built releases, update the tooling to use them.

To build your own build-from-source, one can do this:
```
docker build --build-arg RESTY_VERSION="1.17.8.1rc1" -f alpine/Dockerfile .
```

I'll hand-build some and push them.   The Travis tooling isn't  set-up to handle mixed versions of releases.

**Comment by ecc256** [comment]
I'm not so sure about it.

I.e. it'll build definitely.
But you might want to use also:
```
ARG RESTY_OPENSSL_VERSION="1.1.1g"
ARG RESTY_PCRE_VERSION="8.44"
```
Some other options should be update probably, like `gcc`?

**Comment by neomantra** [comment]
The latest `alpine` flavors use those build-args for OpenSSL and PCRE.  `gcc` gets installed during the build process, but is removed.

Also related, we will be moving `alpine` to use the upstream packages (#142).

I've built using the build line above (`--build-arg RESTY_VERSION="1.17.8.1rc1"`), but I have not pushed any images.

**Comment by ecc256** [comment]
Evan,
Could you clarify, please:
Does any gcc options [suppose to be] different for v1.17.8.1rc1 and 1.15.8.3?
Thanks

**Comment by neomantra** [comment]
For the Docker packaging, I rely on the upstream (official OpenResty) build process.  So I don't know the answer to your question.   If you are having specific gcc issues, check out the main OpenResty GitHub or mailing list.  You will get a more qualified response there.

I've only built the 1.17 images, I haven't tested them at all -- this is why I haven't pushed any images yet.

**Comment by ecc256** [comment]
Bump! 👍

**Comment by neomantra** [comment]
Thanks for the bump -- I see these it was released yesterday.  I'll give it some love today and if there's no issues should have images live by tomorrow.

**Comment by ecc256** [comment]
Thanks! :)

**Comment by neomantra** [comment]
I updated the images but have not updated the git tags.  

I'd appreciate any feedback as to how they are behaving... I don't have a good QA setup for these and mostly rely on upstream.

**Comment by neomantra** [comment]
I've tagged `1.17.8.1-0`

**Comment by neomantra** [comment]
I've also just tagged `1.17.8.2-0`
