### ISSUE TITLE
lack of bcrypt support

### ISSUE THREAD

**Issue by hryamzik** [openresty/docker-openresty#141]
`crypt_r() failed (22: Invalid argument)` when password is generated with `bcrypt` on `openresty/openresty` image.

Nginx seem to rely on `crypt()` schemes provided by OS.

**Comment by neomantra** [comment]
Which image tag are you using?   I did some quick research and it's not clear where to get that for alpine (without building it ourselves).   If you are using Debian variants, does installing the `bcrypt` package work for you?

I note the upstream OpenResty packages don't include bcrypt support -- I wonder if there's a reason for that.

**Comment by hryamzik** [comment]
`latest`, it's debian based:

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```

**Comment by neomantra** [comment]
Install the `bcrypt` package and let me know how it works.  I'd add it to the built-from-source Debian flavors.  But I try to keep the upstream flavors matching upstream.

**Comment by hryamzik** [comment]
No, that doesn't help. Otherwise I would've already fired a PR.

**Comment by neomantra** [comment]
Hmmm... it seems that nginx's images have this issue with Debian, but not with Alpine.  And that it is not easy for a Docker image to fix it:
https://github.com/nginxinc/docker-nginx/issues/29

If you really need bcrypt support, perhaps try `openresty/openresty:alpine` ?

**Comment by hryamzik** [comment]
alpine works fine, thanks!
