### ISSUE TITLE
Use the official alpine repos for alpine images

### ISSUE THREAD

**Issue by agentzh** [openresty/docker-openresty#142]
Let's use the official alpine apk repos for alpine images wherever possible:

https://openresty.org/en/linux-packages.html

https://openresty.org/en/apk-packages.html

**Comment by neomantra** [comment]
Great, I didn't know you had upstream Alpine packages ready.    I'll transition the images this month.

**Comment by neomantra** [comment]
These images live as `alpine-apk` flavor.   There are still built-from-source flavors `alpine` and `alpine-fat`.
