### ISSUE TITLE
ARG RESTY_RPM_ARCH="x86_64" should be replaced with aarch64 in centos/Dockerfile?

### ISSUE THREAD

**Issue by mywulin** [openresty/docker-openresty#143]
https://github.com/openresty/docker-openresty/blob/master/centos/Dockerfile#L18
I am building openresty image for centos, is it a typo here for RESTY_RPM_ARCH？

```
ARG RESTY_RPM_ARCH="x86_64"
```

**Comment by neomantra** [comment]
It is not a typo.  `x86_64` is for 64-bit x86 systems, whereas `aarch64` is for 64-bit ARM systems.

The [OpenResty Linux Packages](http://openresty.org/en/linux-packages.html) page shows the supported OS versions and architectures.   It looks like `aarch64` is supported for CentOS 7.

In the Docker packaging, we do not build ARM images (#130), but if you have an ARM system, you can try to do so yourself with:
```
docker build -f centos/Dockerfile --build-arg RESTY_RPM_ARCH="aarch64" .
```

If you do try that, please let me know how it works as I don't have access to ARM servers.

**Comment by mywulin** [comment]
It works for me with some changes below:

```

# Configure proxy
ENV http_proxy http://ip:port
ENV https_proxy http://ip:port

RUN echo proxy=http://ip:port >>/etc/yum.conf
RUN echo sslverify=false >>/etc/yum.conf

RUN yum makecache \
    && yum reinstall -y ca-certificates \
    && update-ca-trust force-enable \
    && update-ca-trust extract

...
# add "--insecure" at the end of the line below
    && curl -fSL https://luarocks.github.io/luarocks/releases/luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz -o luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz --insecure \
...
```

**Comment by neomantra** [comment]
Thanks for the feedback.   I haven't used this myself, but if you need a proxy, you can [configure your Docker client to use a proxy](https://docs.docker.com/network/proxy/) rather than changing the Dockerfile.
