### ISSUE TITLE
How do I include nginx-upload-module for my nginx 

### ISSUE THREAD

**Issue by Sargababu** [openresty/docker-openresty#144]
I am trying to host an nginx server using openresty. Below is the docker file content I have

```
FROM openresty/openresty:1.15.8.3-buster
ENV UPLOAD_MODULE_VERSION 2.3.0
ENV UPLOAD_FOLDER /upload
RUN CONFIG="\
            --conf-path=/etc/nginx/nginx.conf \
            --with-debug \
            --with-stream \
            --user=nginx \
            --group=nginx \
            --add-module=/usr/src/nginx-upload-module-$UPLOAD_MODULE_VERSION "\
            && groupadd nginx \
            && useradd -g nginx  -s /sbin/nologin nginx \
            && ./configure $CONFIG
#RUN addgroup nginx && \
#   adduser --group nginx --disabled-login && \
#   ./configure $CONFIG
RUN mkdir "$UPLOAD_FOLDER" && chown nginx:nginx -R "$UPLOAD_FOLDER"
VOLUME /upload
# Remove default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy nginx configuration configuration
COPY nginx.conf /etc/nginx/nginx.conf
COPY config/upload-config.conf /etc/nginx/conf.d/upload-config.conf

CMD ["nginx", "-g", "daemon off;"]
```

On trying to build the docker image it complaints saying ./configure not found.

**Comment by rainingmaster** [comment]
It seems `openresty/openresty:1.15.8.3-buster` is come from [this Dockerfile](https://github.com/openresty/docker-openresty/blob/master/buster/Dockerfile#L43), and the Openresty is install by `apt`, it should not pack with source code.

Maybe you should write your own Dockerfile with source code and build with `nginx-upload-module`.

**Comment by neomantra** [comment]
The [`bionic` flavor](https://github.com/openresty/docker-openresty/blob/master/bionic/Dockerfile) builds from source.  For some use cases, you can customize the image build without making your own Dockerfile through [Docker build arguments](https://github.com/openresty/docker-openresty/#building-from-source).

**Comment by Sargababu** [comment]
Thanks @neomantra @rainingmaster  for your inputs. Will try
