### ISSUE TITLE
FROM openresty/openresty:alpine - failed to load the 'resty.core' module

### ISSUE THREAD

**Issue by indera-shsp** [openresty/docker-openresty#148]
We started to get these errors today

2020/07/09 15:19:55 [alert] 1354#1354: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file '/etc/nginx/resty/core.lua'
	no file '/usr/local/openresty/site/lualib/resty/core.so'
	no file '/usr/local/openresty/lualib/resty/core.so'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so') in /usr/local/openresty/nginx/conf/nginx.conf:287

==== Our solution was to hard-code an older version
```
FROM openresty/openresty:1.15.8.3-2-alpine
```

**Comment by neomantra** [comment]
Can you paste what image flavor and commands you are running? 

I assume you are running from the images without version tags, such as `openresty/openresty:centos`?

Then that would be the latest images (rather than pinned version).   So these newest images use OpenResty 1.17.8.1, so your failure probably is related to that.   I'll try to help with more detail.

**Comment by neomantra** [comment]
Sorry, I missed that the flavor (`alpine`) was in the issue description.

It looks like `resty.core` is now automatically loaded.  That and other changes are listed here:
http://openresty.org/en/changelog-1017008.html

What does your `nginx.conf` look like around line 287?

**Comment by indera-shsp** [comment]
Line 287 just ends this block
```
http {
    include                     /etc/nginx/mime.types;
    lua_package_path            "/etc/nginx/?.lua";
    init_by_lua '
        whitelist = require("whitelist").init()
    ';
....

}

**Comment by neomantra** [comment]
`resty/core.lua` is found in the same place in both versions: `/usr/local/openresty/lualib/resty/core.lua`

Perhaps something is wrong with your package path?  You are overriding it to just `/etc/nginx` -- OpenResty doesn't install any Lua there.   One thing would be to add `;;` to the beginning of the search path to include the default path.   But I'm wondering how that even works with `1.15` series.

**Comment by tmegow** [comment]
@neomantra Thank you! your comment helped @indera-shsp and myself fix our broken upgrade. 👍  We're now using `v1.17.8.1` successfully.
