### ISSUE TITLE
Usage of luarocks in docker container

### ISSUE THREAD

**Issue by gitrus** [openresty/docker-openresty#15]
Hello,
I'm using your xenial image like a parent for my image and install some packages with "/usr/local/openesty/luajit/bin/luarocks install <rock>" none of them can't be detected by Lua scripts.
`FROM openresty/openresty:latest-xenial`

`WORKDIR /opt`

`RUN /usr/local/openresty/luajit/bin/luarocks install lbase64 \`
`  && /usr/local/openresty/luajit/bin/luarocks install lzlib 0.4.work3-1 \`
`  && /usr/local/openresty/luajit/bin/luarocks install xml \`
`  && /usr/local/openresty/luajit/bin/luarocks install lua-resty-http \`
`  && mkdir /opt/ssl && mkdir /opt/proxy`

`EXPOSE 5080`

**Comment by neomantra** [comment]
I cannot reproduce.   Are you using the LuaJIT interpreter that is bundled with OpenResty?  The image's LuaJIT and luarocks are both configured to use `/usr/local/openresty/luajit` as a Lua install prefix.   If you use some other Lua interpreter, you need to update your `LUA_PATH` and `LUA_CPATH`.

If you can provide a test case, I will look deeper.

Here I show it working and where it installs to and the package paths:
```
$ docker run -it --entrypoint=/bin/bash openresty/openresty:xenial

root@12f0dc9138a1:/# /usr/local/openresty/luajit/bin/luarocks install md5
Installing https://luarocks.org/md5-1.2-1.src.rock...
Using https://luarocks.org/md5-1.2-1.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/compat-5.2.c -o src/compat-5.2.o -Isrc/
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/md5.c -o src/md5.o -Isrc/
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/md5lib.c -o src/md5lib.o -Isrc/
gcc -shared -o md5/core.so -L/usr/local/openresty/luajit/lib src/compat-5.2.o src/md5.o src/md5lib.o
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/compat-5.2.c -o src/compat-5.2.o -Isrc/
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/des56.c -o src/des56.o -Isrc/
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/ldes56.c -o src/ldes56.o -Isrc/
gcc -shared -o des56.so -L/usr/local/openresty/luajit/lib src/compat-5.2.o src/des56.o src/ldes56.o
Updating manifest for /usr/local/openresty/luajit/lib/luarocks/rocks
No existing manifest. Attempting to rebuild...
md5 1.2-1 is now built and installed in /usr/local/openresty/luajit (license: MIT/X11)

root@12f0dc9138a1:/# find / -name md5
/usr/local/openresty/luajit/lib/luarocks/rocks/md5
/usr/local/openresty/luajit/lib/lua/5.1/md5

root@12f0dc9138a1:/# /usr/local/openresty/luajit/bin/luajit -e "print(package.path, '\n', package.cpath, '\n', require('md5'))"
./?.lua;/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua	
./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
table: 0x40429020
```

**Comment by gitrus** [comment]
I try to explain my problem with sample:

Here the gist: https://gist.github.com/gitrus/60eba5f23ba7f05d271ce305ac6b58d9
file tree:
sample-proxy/
|--lua/
|----indx.lua
|--proxy.conf

`docker run -v ../sample-proxy:/opt/proxy proxy`

with bash i run `/usr/local/openresty/bin/openresty /opt/proxy/proxy.conf`
and try `curl localhost:5080/indx`

get error about require module `xml`.

**Comment by neomantra** [comment]
It took me a bit to see this... your issue is on line 10 of proxy.conf:

 * `lua_package_path '/opt/proxy/?.lua;';`

should be:

* `lua_package_path '/opt/proxy/?.lua;;';`

Note the extra semicolon, without it, you are hiding the default search paths.  See  https://github.com/openresty/lua-nginx-module#lua_package_path

Let me know if you continue to have issues after fixing that.

**Comment by gitrus** [comment]
Thank you for your help.
Yes, it resolve issue.
