### ISSUE TITLE
Fedora Image to be made available on DockerHub.

### ISSUE THREAD

**Issue by kshitijmjoshi** [openresty/docker-openresty#152]
Can we please have the openresty:fedora image available on DockerHub?
https://hub.docker.com/r/openresty/openresty

**Comment by neomantra** [comment]
I was just working on that -- It is running in CI right now... 
https://travis-ci.org/github/openresty/docker-openresty
Should be on the hub eventually... and in the next tag.  Thanks for the contribution

**Comment by kshitijmjoshi** [comment]
@neomantra Thanks!

**Comment by kshitijmjoshi** [comment]
@neomantra Not sure how the Readme.md on the 
https://hub.docker.com/r/openresty/openresty would be updated.

**Comment by neomantra** [comment]
This is in `1.17.8.2-1`.  I update Docker Hub page manually.
