### ISSUE TITLE
Debian buster cannot start service

### ISSUE THREAD

**Issue by clarkttfu** [openresty/docker-openresty#155]
Image: 
https://hub.docker.com/layers/openresty/openresty/buster-fat/images/sha256-cabed7781efb2993f045f844f2cca9687bfa0686ad28a7cf5f93ffa6905e0667?context=explore

Reproduce:

```
> service openresty status
/etc/init.d/openresty: 27: .: Can't open /lib/lsb/init-functions
```

Expect:

The service could be started.

**Comment by clarkttfu** [comment]
The [lsb-base package](https://packages.debian.org/buster/all/lsb-base/filelist) is missed:
`/lib/lsb/init-functions` is required by `/etc/init.d/openresty`

PR is reeady:  #156

**Comment by neomantra** [comment]
Thanks for the issue and PR.   Will be in tag `1.17.8.2-2` once Travis is all done.
