### ISSUE TITLE
[centos-rpm] OpenSSL conflicts

### ISSUE THREAD

**Issue by karai17** [openresty/docker-openresty#161]
I am trying to build a Docker image using openresty's official image as a base. According to the following bug report, both RedHat and Luaossl backported a feature from OpenSSL 1.2 to OpenSSL 1.1 and this double-backport is causing conflicts.

https://github.com/wahern/luaossl/issues/175

The proposed solution is to supply Luaossl with additional build flags so that it doesn't try to redefine definitions already defined by RedHat:

`RUN luarocks install luaossl CFLAGS="-O2 -fPIC -DHAVE_EVP_KDF_CTX=1"`

This works in that Luaossl builds, but when I am trying to run my Lapis application, I get the following error:

```sh
web_1   | 2020/09/23 01:10:18 [error] 21#21: *1 lua entry thread aborted: runtime error: error loading module '_openssl.hmac' from file '/usr/local/openresty/luajit/lib/lua/5.1/_openssl.so':
web_1   |       /usr/local/openresty/luajit/lib/lua/5.1/_openssl.so: undefined symbol: EVP_KDF_size, version OPENSSL_1_1_1b
web_1   | stack traceback:
web_1   | coroutine 0:
web_1   |       [C]: in function 'require'
web_1   |       content_by_lua(nginx.conf.compiled:33):1: in main chunk, client: 172.22.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:1001"
```

From the error message, it appears that the `_openssl.so` provided by openresty does not have this backported feature, but the system OpenSSL, which appears to not be invoked, does?

**Comment by neomantra** [comment]
I recall seeing another issue somewhere sorta like this... try building `luaossl` against OpenResty's OpenSSL library?

**Comment by karai17** [comment]
How would I go about doing that? The Luarocks documentation leaves a lot to be desired.

**Comment by neomantra** [comment]
This might be what I was thinking of: #36  

Maybe this helps too: https://github.com/leafo/lapis/issues/632
In that bug they have this:
```
/usr/local/openresty/luajit/bin/luarocks install lapis CRYPTO_DIR=/usr/local/openresty/openssl/ OPENSSL_DIR=/usr/local/openresty/openssl/ 
```

The directory is `/usr/local/openresty/openssl111/lib` ?
```
$ docker run -it --rm  --entrypoint=/bin/bash openresty/openresty:centos-rpm  -c "ls /usr/local/openresty/openssl111/lib"
engines-1.1  libcrypto.so  libcrypto.so.1.1  libssl.so	libssl.so.1.1
```

**Comment by karai17** [comment]
No bueno. OpenResty does not provide source files and the source files provided by the system have the same backport conflict, as expected.

`RUN luarocks install lapis CRYPTO_DIR=/usr/local/openresty/openssl111/ CRYPTO_INCDIR=/usr/include/ OPENSSL_DIR=/usr/local/openresty/openssl111/ OPENSSL_INCDIR=/usr/include/`

**Comment by karai17** [comment]
Unless I am mistaken, there seems to be a few possible solutions, none of which I have much control over:

1) RedHat removes the backported feature (this would be bad)
2) Luaossl removes the backported feature and relies on systems to provide it (more reasonable)
3) Both RedHat and Luaossl keep the backported feature but Luaossl first checks the OpenSSL it is building against to see if it needs to enable that or not (most reasionable; RedHat mention this to Luaossl who in turn claims RedHat's backport is a "bug")
4) OpenResty provides the include files and anything else needed so that rocks can be built against its internal OpenSSL version

**Comment by karai17** [comment]
I've fixed the issue! I needed to also install `openresty-openssl-devel`:

```sh
RUN yum -y install openssl-devel openresty-openssl-devel
RUN luarocks install lapis CRYPTO_DIR=/usr/local/openresty/openssl/ CRYPTO_INCDIR=/usr/local/openresty/openssl/include OPENSSL_DIR=/usr/local/openresty/openssl/ OPENSSL_INCDIR=/usr/local/openresty/openssl/include
```
