### ISSUE TITLE
关于添加新的第三方module

### ISSUE THREAD

**Issue by zywayh** [openresty/docker-openresty#163]
您好，想请问一下，如果添加第三方的module？在centos的dockerfile中，/tmp/luarocks-${RESTY_LUAROCKS_VERSION}被删掉了，无法使用configure命令，如何才能快速的添加呢？

**Comment by neomantra** [comment]
I put your issue into Google Translate.   Can you be more specific in what you are trying to do?  Install a Lua Rock?  Install an NGINX module?

The Dockerfile removes the build artifacts of `luarocks` but the `luarocks` command itself is installed and available in that image:
```
$ # Invoke luarocks within a container:
$ docker run -it --rm --entrypoint=luarocks openresty/openresty:1.17.8.2-5-centos
Usage: luarocks [-h] [--version] [--dev] [--server <server>]
       [--only-server <server>] [--only-sources <url>
.....
```

So you can make your own Dockerfile that derives from these images and invokes `luarocks`.  See the last line of this [example Dockerfile](https://github.com/openresty/docker-openresty/blob/master/buster/Dockerfile.luarocks_example#L43).

**Comment by zywayh** [comment]
Thanks for you reply. To add a new mudole, you need to use ./configure --add-module = XXX, but configure seems to be deleted in dockerfile. The configure command cannot be used again.

**Comment by neomantra** [comment]
I see, so you mean an Nginx module, not a Lua package.   I was confused as you mentioned `/tmp/luarocks-${RESTY_LUAROCKS_VERSION`.

The `centos` image is derived from OpenResty [upstream RPM packages](https://openresty.org/en/rpm-packages.html).  The `./configure` you were pointing at is for building LuaRocks, not OpenResty.

If you want to add your own Nginx modules, you need to use build-from-source images.  See [this part of the README](https://github.com/openresty/docker-openresty) and [this Dockerfile](https://github.com/openresty/docker-openresty/blob/master/bionic/Dockerfile).  We lets you inject code and CLI arguments in the build process using `--build-arg`.

You probably want to play with:
 * `RESTY_CONFIG_OPTIONS_MORE` 
 * `RESTY_EVAL_PRE_CONFIGURE` 
 * `RESTY_EVAL_POST_MAKE`

If you get something working and can share, post it here so future users can see.

**Comment by neomantra** [comment]
Closing as stale
