### ISSUE TITLE
brotli support

### ISSUE THREAD

**Issue by jney** [openresty/docker-openresty#164]
Hello, is there any brotli support planned?

**Comment by neomantra** [comment]
We generally keep module parity with upstream OpenResty. If it is there and missing from the Docker images, I will add it. 

If you want to add a dynamic module, you can do that with the build-from-source images and Docker build arguments.   This came up recently in this issue #163

**Comment by jney** [comment]
thank you for your reply. It is not in upstream OpenResty. I'll try to install it the way you pointed me out

**Comment by neomantra** [comment]
Great, if you come up with something please put it here and I’ll try to incorporate it into the docs.

**Comment by neomantra** [comment]
Closing as stale
