### ISSUE TITLE
Nginx syntax error for 1.17.8.2-5-buster-fat: "resolver" directive is not allowed in upstream

### ISSUE THREAD

**Issue by mohsenasm** [openresty/docker-openresty#165]
Hi,
As [Nginx documentation says](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#resolver), for Nginx 1.17.5+, we can use the `resolver` directive in the `upstream`s. Usage Like:

```
upstream hostname_x_upstream {
    resolver 127.0.0.11 ipv6=off;

    server hostname-a;
    server hostname-b;
    server hostname-c;
}
```

And I've expected that the version `1.17.8.2-5-buster-fat` of `openresty/openresty` image is compatible with the Nginx 1.17.8.

But it isn't. I see these errors in the logs:
```
container_name.1.s8nd7stbczvv@s-3    | nginx: [emerg] "resolver" directive is not allowed here in /etc/nginx/conf.d/file_name.conf:23
```

**Comment by neomantra** [comment]
From your documentation link, it says `This directive is available as part of our commercial subscription.`

Can you confirm that your `upstream` directive works on plain Nginx or non-Dockerized OpenResty?

**Comment by mohsenasm** [comment]
Oh, Thanks for your response.
That was a misunderstanding. I close the issue.

**Comment by neomantra** [comment]
No worries -- if you search around you'll see blog posts using OpenResty DNS modules to get a similar effect.  I haven't done it myself, so I can't recommend a particular one.
