### ISSUE TITLE
openresty 1.19.3.1 docker

### ISSUE THREAD

**Issue by dannygueta** [openresty/docker-openresty#167]
Hi, 

any plans to release an updated alpine based container for 1.19.3.1 ? 

Thanks.

**Comment by neomantra** [comment]
Soon, there's this PR #166  if you want to follow it.

**Comment by neomantra** [comment]
This was tagged and released this morning along with the other flavors.

`docker pull openresty/openresty:1.19.3.1-0-alpine`
