### ISSUE TITLE
openssl error when building openresty from source on alpine3.13

### ISSUE THREAD

**Issue by andrewzah** [openresty/docker-openresty#178]
I've documented the error and context in https://github.com/openssl/openssl/issues/14974.

I'm using the [alpine Dockerfile](https://github.com/openresty/docker-openresty/blob/master/alpine/Dockerfile).

**Comment by neomantra** [comment]
I tried this in a clean environment and cannot duplicate.  From in the repo can you try:
```
 docker build -f alpine/Dockerfile --no-cache  --pull .
```

Sometimes there are weird errors when memory or disk aren't available to the build machine.

**Comment by andrewzah** [comment]
Changing from alpine3.13 to alpine3.12 fixed this. Apparently 3.14 introduces a fix for it as well.
