### ISSUE TITLE
Need to update docker images to 1.19.3.2 with security fixes

### ISSUE THREAD

**Issue by agentzh** [openresty/docker-openresty#181]
See https://openresty.org/en/ann-1019003002.html

**Comment by neomantra** [comment]
Thanks for letting me know -- I'll do this today.

**Comment by neomantra** [comment]
I released `1.19.3.2-0` with just the version upgrade.

Then released `1.19.3.2-1`, which builds multi-architecture images (`amd64`, `aarch64`) for all the supported flavors, except Windows.
