### ISSUE TITLE
Migrate to our official pre-built packages for our aarch64/arm64 docker images wherever possible

### ISSUE THREAD

**Issue by agentzh** [openresty/docker-openresty#183]
Recently we added a lot of new yum/apt/apk repositories for openresty here:

https://openresty.org/en/linux-packages.html

Better migrate our aarch64/arm64 docker images (if any?) over to use these packages directly. Thanks!

**Comment by neomantra** [comment]
@agentzh Also, I seem to have run out of Travis build minutes.... did OpenResty adopt Travis-ci.com?

Otherwise, I might move these builds to Gitlab.com as I have a commercial plan there -- it is easier for me to donate minutes from there or apply for their OSS license.

**Comment by neomantra** [comment]
OK so there are multi-arch builds for all flavors now... except Buster (no `arm64`)
