### ISSUE TITLE
Add arm64/aarch64 images for buster

### ISSUE THREAD

**Issue by skirkpatrick** [openresty/docker-openresty#184]
arm64 packages for buster are available at https://openresty.org/package/arm64/debian/pool/openresty/o/openresty/. Would it be possible to publish arm64 image variants for buster?

**Comment by neomantra** [comment]
Great, it wasn't available at the time of #183.   And it looks like Travis is processing it, so that's great.... will be tagged soon.

**Comment by neomantra** [comment]
Taggged `1.19.3.2-2`
