### ISSUE TITLE
docker hub readme points to missing xenial/ in github

### ISSUE THREAD

**Issue by iakkus** [openresty/docker-openresty#185]
Thanks for the Dockerfiles!

I don't know how else to bring this to your attention except for here. 

The docker hub readme doesn't match the github repo readme and links to non-existing xenial/ folder in github. In addition, the focal/ is missing there even though it exists in github.

**Comment by neomantra** [comment]
You're welcome!  Glad it might be helpful for you.

This is exactly the right place to mention that issue.  That's a manual process I often forget to do ... I just updated that now.  Thanks!
