### ISSUE TITLE
update docker images to support 1.19.9.1

### ISSUE THREAD

**Issue by sp-xray** [openresty/docker-openresty#188]
Hi

Openresty 1.19.9.1 released a week ago. more info: https://openresty.org/en/ann-1019009001.html
does adding support for it is on the way?

**Comment by neomantra** [comment]
Thanks for the notification -- I'll take care of a release today.

**Comment by neomantra** [comment]
Blocked also by this:
https://github.com/openresty/openresty-packaging/issues/66

**Comment by neomantra** [comment]
I've worked through building Alpine 3.14 images and just released `1.19.9.1-0`. 

https://app.travis-ci.com/github/openresty/docker-openresty/builds/235626147

**Comment by sp-xray** [comment]
👍 thank you!
