### ISSUE TITLE
Debian stable?

### ISSUE THREAD

**Issue by roy-work** [openresty/docker-openresty#191]
The images available on DockerHub appear to be based on oldstable/("`buster`"), rather than the current stable version, `bullseye`.

**Comment by neomantra** [comment]
Noting this [upstream issue](https://github.com/openresty/openresty-packaging/issues/56)... will see if it's ready to put here yet

**Comment by neomantra** [comment]
OK, looks like it's there... will release tonight... more links for future:

 * https://blog.openresty.com/en/openresty-pre-built-for-debian-11/?src=org_news
 * https://openresty.org/package/debian/pool/openresty/o/openresty/

**Comment by neomantra** [comment]
`bullseye` and `bullseye-fat` tags were released in `1.19.9.1-2`
