### ISSUE TITLE
Need to trigger an alpine build to use new release Alpine 3.14.3

### ISSUE THREAD

**Issue by tobybellwood** [openresty/docker-openresty#195]
Hi - Just checking whether it's possible for you to trigger a new Travis run to pick up the recent Alpine 3.14.3 [release](https://alpinelinux.org/posts/Alpine-3.14.3-released.html) and push a new set of openresty/openresty (alpine) images to docker hub

I've built and tested all three (alpine, alpine-apk and alpine-fat) locally and they all build and run ok, and show 3.14.3 without the busybox and openssl vulnerabilities.

**Comment by neomantra** [comment]
Thanks for the heads up.  I'm releasing `1.19.9.1-3` for #193 tonight, which should also fix this.

**Comment by tobybellwood** [comment]
beautiful!

thanks for all your work on this, we use these images everywhere at @uselagoon!

**Comment by neomantra** [comment]
You are welcome!  That is pushed.
