### ISSUE TITLE
should this image do more than build OpenResty

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#2]
Right now this image just builds OpenResty.  People can build on top of this to make more complex deployments and simply use this as a their Dockerfile `FROM` command.  Since OpenResty is so flexible, perhaps this is all it should do.

The nginx docker image includes a default `nginx.conf` file for serving static content and exposes ports 80 and 443 (which can be remapped at run-time).

We have to be careful of being too tailored to the nginx case because this image can also be used for running `resty`.   

Perhaps we just document the different ways to use it in the README.   nginx does that.

**Comment by agentzh** [comment]
@neomantra Yeah, there are various different ways to run OpenResty. Feel free to document various different uses in README :)

**Comment by SkyLothar** [comment]
:+1: 

Will you consider including following packages?
They are extremely useful for developers who wants to run lua module tests using docker.

- [Test::Nginx](https://github.com/openresty/test-nginx)
- [LuaRocks](https://github.com/keplerproject/luarocks)

**Comment by pataquets** [comment]
Unless running tests are necessary to build the image (QA), I'll leave the image as minimal and common-usage possible. Since Docker layered image filesystem encourages building from previous parent images, I would leave other, more specific, use cases to other (child) images based on this one. Think for example on openresty-dev to include LuaRocks & Test::Nginx.

+1 on keeping this minimal.

**Comment by ruslantalpa** [comment]
Please consider this usecase:
Usually in docker, you base your image of an existing one (for example openresty/openresty:alpine) and then you bake in the configs and other tools, and that works fine as long you are happy with the built openresty version/modules
However if you want custom modules, you can no longer use the base image, you have to clone the repo and change the docker file.

How about splitting the current docker files in 2 parts. The first file/image (build env) would set up the build env and the other image (compile) will be based on the "build env" and execute the last step of building openresty and cleaning up after the build.

This way, if i am happy with the official modules, i extend the "compile" docker image, if i need a custom build, then i extend the "build env" image, override the RESTY_CONFIG_OPTIONS and execute the last stage (not sure the "compile" docker file can see the things defined in "build env").

As a conclusion, my question is really how can the official openresty image be setup to allow custom openresty builds without the need to clone the repo and change the Docker file

Thank you

**Comment by neomantra** [comment]
For custom builds, don't you only need to change the Dockerfile if your new configure options require new dependencies?   I actually just faced this in adding a bunch of modules to the default list (e.g. `geoip-dev` needed to be installed).   One thing that would make this more flexible would be to make the installed packages a `--build-arg` as well.  Either way you are still cloning a repo -- its just that the modifications go at the command line rather than in the Dockerfile, which is probably beneficial for a build script.   However, injectable dependencies doesn't help when your dependency isn't available in the package manager.

Downsides to splitting into two:
 * double the amount of Dockerfiles
 * bigger image layers (although the non-alpine ones are already thick)

I've also tried to make the image clean and readable so people can just make their own base Dockerfile from it.  Although there is appeal to `docker pull openresty/openresty:latest`, I often find I'm rolling my own version of a Dockerfile for my own purposes (I'm speaking generally to Docker, no this OpenResty one).

Can you give a concrete example of how this might work?   Do you mean like split the image right before the `./configure` line?  Also, how does dynamic module loading (available in the latest 1.9.15.1 images) affect what you are thinking about?

**Comment by ruslantalpa** [comment]
I am not sure how all of this can work (just trying docker out), i was just pointing out a "problem/inconvenience" hoping someone has a solution. I will be playing with this for the next couple of days and if i find a solution i will post back here

PS (unrelated): i just noticed the alpine image is 165M, that is because of gcc, will post to the relevant issue if i find a solution to make it smaller

**Comment by neomantra** [comment]
Great -- this is all new and I am open to other ways of doing things if it makes sense.

The Alpine image grew from 14MB to 42MB because of #5.  Then adding all the modules made it grow to 58MB.   Maybe some more of the Alpine cruft can get removed (perl and readline?), but the biggest is the gcc dep from #5 .   Maybe I'll just copy out the file that is needed by LuaJIT.  The non-alpine images are much bigger, but have less cleanup work done.

**Comment by ruslantalpa** [comment]
After giving it some thought, the direction you are going it is good, the only thing that needs to change is to have {build_dependencies} and {runtime_dependencies} arguments that are installed with apk/apt-get.
This will give great flexibility when building your custom openresty.
Once you build that, you use it as your base image to which you add your configs and stuff like that
(this is starting to look pretty great :) )

**Comment by neomantra** [comment]
Closing -- if there are concrete suggestions please open as a discrete issue.
