### ISSUE TITLE
openresty 1.21.4.1 docker

### ISSUE THREAD

**Issue by xiaocang** [openresty/docker-openresty#206]
Hi, @neomantra, we've uploaded packages of 1.21.4.1 for rpm, deb, and apk, would you please help to release the docker hub ones

**Comment by neomantra** [comment]
Working on this -- waiting on some ARM packages to land -- expect it to be done today or tomorrow.
See: https://app.travis-ci.com/github/openresty/docker-openresty/builds/250800162

**Comment by xiaocang** [comment]
Hi @neomantra , the aarch64 packages are ready now

**Comment by neomantra** [comment]
Still missing Debian and Ubuntu `arm64`:
 * https://openresty.org/package/arm64/debian/pool/openresty/o/openresty/
 * https://openresty.org/package/arm64/ubuntu/pool/main/o/openresty/

**Comment by xiaocang** [comment]
It looks like it was missed

**Comment by xiaocang** [comment]
Hi @neomantra, the packages have been uploaded, so you can move on

**Comment by neomantra** [comment]
This has been released as tag `1.21.4.1-0`
