### ISSUE TITLE
Add s390x support to docker images

### ISSUE THREAD

**Issue by kun-lu20** [openresty/docker-openresty#208]
Hi,

Since OpenResty could be built from source on s390x with similar steps to amd64 arch now, and Travis CI has s390x support as well, we would greatly appreciate it if community can provide official s390x docker images.

The existing Dockerfiles need to be adjusted slightly to exclude PCRE build steps which do not support s390x yet. If community agrees to add s390x to "build-from-source" flavors, I can raise a PR to add Dockerfiles for s390x.

Thanks!

**Comment by kun-lu20** [comment]
Thanks @neomantra !

Sure, below is the diff log for the Ubuntu focal Dockerfile:

```diff
diff --git a/focal/Dockerfile b/focal/Dockerfile
index b5d0879..975e90f 100644
--- a/focal/Dockerfile
+++ b/focal/Dockerfile
@@ -94,6 +94,7 @@ RUN DEBIAN_FRONTEND=noninteractive apt-get update \
         libperl-dev \
         libreadline-dev \
         libxslt1-dev \
+        libpcre3-dev \
         make \
         perl \
         unzip \
@@ -124,19 +125,6 @@ RUN DEBIAN_FRONTEND=noninteractive apt-get update \
     && make -j${RESTY_J} \
     && make -j${RESTY_J} install_sw \
     && cd /tmp \
-    && curl -fSL https://downloads.sourceforge.net/project/pcre/pcre/${RESTY_PCRE_VERSION}/pcre-${RESTY_PCRE_VERSION}.tar.gz -o pcre-${RESTY_PCRE_VERSION}.tar.gz \
-    && echo "${RESTY_PCRE_SHA256}  pcre-${RESTY_PCRE_VERSION}.tar.gz" | shasum -a 256 --check \
-    && tar xzf pcre-${RESTY_PCRE_VERSION}.tar.gz \
-    && cd /tmp/pcre-${RESTY_PCRE_VERSION} \
-    && ./configure \
-        --prefix=/usr/local/openresty/pcre \
-        --disable-cpp \
-        --enable-jit \
-        --enable-utf \
-        --enable-unicode-properties \
-    && make -j${RESTY_J} \
-    && make -j${RESTY_J} install \
-    && cd /tmp \
     && curl -fSL https://openresty.org/download/openresty-${RESTY_VERSION}.tar.gz -o openresty-${RESTY_VERSION}.tar.gz \
     && tar xzf openresty-${RESTY_VERSION}.tar.gz \
     && cd /tmp/openresty-${RESTY_VERSION} \
@@ -146,7 +134,6 @@ RUN DEBIAN_FRONTEND=noninteractive apt-get update \
     && cd /tmp \
     && rm -rf \
         openssl-${RESTY_OPENSSL_VERSION}.tar.gz openssl-${RESTY_OPENSSL_VERSION} \
-        pcre-${RESTY_PCRE_VERSION}.tar.gz pcre-${RESTY_PCRE_VERSION} \
         openresty-${RESTY_VERSION}.tar.gz openresty-${RESTY_VERSION} \
     && curl -fSL https://luarocks.github.io/luarocks/releases/luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz -o luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
     && tar xzf luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
```

**Comment by neomantra** [comment]
I just got an IBM Cloud s390x VM on the free tier -- I should be fine for a bit.   

I see that PCRE is not building because its JIT is not supported on `s390x` ?   I was looking at the Ubuntu version and I think they simply build it without JIT support?  It's clear that's what is [happening in Alpine](https://git.alpinelinux.org/aports/tree/main/pcre/APKBUILD#n42).

It seems there is discussion about this:
https://github.com/zherczeg/sljit/issues/89

All of this affect the [upstream ticket](https://github.com/openresty/openresty/issues/834) too.

So I will not take your approach of using the system PCRE, but rather modify the Dockerfiles to accept JIT-less PCRE build and note it in the README.

**Comment by kun-lu20** [comment]
@neomantra Yes, JIT in PCRE is not supported on s390x yet. Thanks for the detailed info!

Sure, disabling the `--enable-jit` option when building PCRE also works. I just tested it locally.

**Comment by neomantra** [comment]
This is released on built-from-source Ubuntu flavors:

 * `openresty/openresty:1.21.4.1-1-bionic`
 * `openresty/openresty:1.21.4.1-1-focal`
 * `openresty/openresty:1.21.4.1-1-jammy`

Have fun!

**Comment by kun-lu20** [comment]
Great! Thanks again @neomantra
