### ISSUE TITLE
debian build images...

### ISSUE THREAD

**Issue by krull** [openresty/docker-openresty#21]
Greetings!

Let me direct your attention to debian builds I did based on your xenial Dockerfile. Both jessie and wheezy build successfully.

On wheezy I had to only reference libgd2-noxpm-dev instead of libgd-dev, and the build succeeded.

You can see it here: https://github.com/krull/docker-openresty

I have left attribution as-is. I just wanted to have an all debian stack versus having to contaminate my stack with some other deb flavor other than debian itself :+1: 

Feel free to include them here for others to use.

Hope this helps!

**Comment by neomantra** [comment]
Somehow I missed this issue.  Thanks for the contribution.   I just added it to the Docker builds.

Long-term I think we will just use the official OpenResty Debian packages, once they exist.   But as you see, it's nice to have a simple example of how to build OpenResty on different systems.

**Comment by krull** [comment]
Nice @neomantra for adding the debian builds! Glad to be of assistance.
