### ISSUE TITLE
Publish debug images to Docker Hub

### ISSUE THREAD

**Issue by mschfh** [openresty/docker-openresty#213]
Please consider publishing `-debug` images to Docker Hub.

nginx includes a `nginx-debug` binary in all images:
https://github.com/docker-library/docs/tree/master/nginx#running-nginx-in-debug-mode

**Comment by yvess** [comment]
I also needed a debug image. Ubuntu main nginx has debug always build in. I also needed a openresty debug image.
You can easy build one, but not ideal if you need on sometimes in production. 

```shell
git clone https://github.com/openresty/docker-openresty.git
cd docker-openresty
docker build --build-arg RESTY_CONFIG_OPTIONS_MORE="--with-debug" -t openresty-debug -f jammy/Dockerfile .
```
