### ISSUE TITLE
Point for command injection after openresty download before configure

### ISSUE THREAD

**Issue by pgibson1-godaddy** [openresty/docker-openresty#219]
Is it possible to get a place to inject custom commands _after_ the openresty download has happened but before the configure happens?

For example it would be ideal right after this line https://github.com/openresty/docker-openresty/blob/1.21.4.1-4/focal/Dockerfile#L146

It could be called something like `RESTY_EVAL_POST_DOWNLOAD_PRE_CONFIGURE` and it would let us run any patches or changes we want to make against the openresty source before compilation.

**Comment by pgibson1-godaddy** [comment]
I added a PR which I believe would do this as well #220

**Comment by neomantra** [comment]
Thanks for the report and the PR.   This makes sense and is a straightforward change, so I can merge this later today.   
I wish that the `RESTY_EVAL_PRE_CONFIGURE` phase was named differently once upon a time, as it's more appropriate for this, but we are stuck :) 

If you wanna be in `AUTHORS.md`, just let me know a name / email (both optional).

**Comment by pgibson1-godaddy** [comment]
@neomantra Awesome - thank you, it will make our build much less hacky!

I don't need any credit in `AUTHORS.md` - thanks for your work. 👍

**Comment by neomantra** [comment]
Oh I think GitHub auto-closed that -- still working on the release.

**Comment by neomantra** [comment]
That is tagged in the repo as `1.21.4.1-5` and building now.  So you can pull GitHub as a base for your image build process.  The Docker images will be ready in a bit.

**Comment by neomantra** [comment]
OK, that's out, thanks again.
