### ISSUE TITLE
ngx_http_upstream_check_module无法添加模块

### ISSUE THREAD

**Issue by shaojie-dot** [openresty/docker-openresty#227]
使用centos7 官方dockerfile安装，发现没有ngx_http_upstream_check_module该模块，怎么添加呢，centos7的dockerfile并没有支持的地方

**Comment by neomantra** [comment]
I do not understand your language, but used Google Translate.

You would need to use the "build-from-source" images and then inject the download / patch / build into the Dockerfile using environment variables.    See this issue #222 for related information.

**Comment by neomantra** [comment]
Closing from inactivity.  Feel free to re-open with updates.
