### ISSUE TITLE
image for new release v1.21.4.2

### ISSUE THREAD

**Issue by yjqg6666** [openresty/docker-openresty#234]
OpenResty 1.21.4.2 was Released at 19 Jul 2023. Announce page is at https://openresty.org/en/ann-1021004002.html.
Updated images are needed.

**Comment by neomantra** [comment]
Thanks for the heads up and congrats to the OpenResty team.  I will work on this today.

**Comment by neomantra** [comment]
This is done and tagged as `1.21.4.2-0`

**Comment by hazmat345** [comment]
Apologies if I'm missing something, but it looks like the images on docker hub are mistagged as 1.**12**.4.2 instead of 1.21.4.2.

**Comment by neomantra** [comment]
Wow, thank you for noticing that -- it takes a village.   Definitely not intentional!   I just fixed that and will watch it through.

**Comment by hazmat345** [comment]
Awesome, thank you!

**Comment by yjqg6666** [comment]
Thanks.

**Comment by yjqg6666** [comment]
@neomantra How about providing Debian 12/Bookworm tagged image? By far the latest tag is based on bullseye. Related issue #232.
