### ISSUE TITLE
Image for new release 1.25.3.1

### ISSUE THREAD

**Issue by HanadaLee** [openresty/docker-openresty#243]
OpenResty 1.25.3.1 was released. https://openresty.org/en/ann-1025003001.html
Updated images are needed.

**Comment by neomantra** [comment]
Thanks for the issue.  I've was working on this over the weekend and now that it is publicly released, I'll wrap it up today or tomorrow.

**Comment by slavikos** [comment]
@neomantra don't forget to include the `--with-http_v3_module` build option 😄 

(I noticed that official deb packages are not built with the http3 option, that's why the comment)

**Comment by neomantra** [comment]
Thanks, I appreciate that comment.  I saw the email this morning and released `1.25.3.1-1`:

https://github.com/openresty/docker-openresty/commit/30682c9b6066ed30740b5e6f9a555549e873529b

That is only for build-from-source flavors... once upstream updates, I'll similarly update.
