### ISSUE TITLE
luajit: unknown luaJIT command or jit.* modules not installed

### ISSUE THREAD

**Issue by yuguangye** [openresty/docker-openresty#249]
When I used the latest `openresty/openresty:1.25.3.1-2-focal` image, I found that we could not use the luajit -bl command, it would output the following error,
<img width="1010" alt="image" src="https://github.com/openresty/docker-openresty/assets/130330966/ab8c56cc-60b4-4abf-8824-49874146f50f">

The reason is that after we upgrade, there is a problem with the directory in the output LUA_PATH environment variable. The jit directory in openresty 1.25.3.1 is /usr/local/openresty/luajit/share/luajit-2.1

The jit directory in openresty 1.21.4.1 is
/usr/local/openresty/luajit/share/luajit-2.1.0-beta3

We need to modify LUA_PATH to work properly

**Comment by neomantra** [comment]
Thanks for pointing this out.  I also note that the LuaJIT binary is now named `luajit-2.1.ROLLING`.  I'm considering making a symlink that is just undecorated `luajit-2.1`.

**Comment by neomantra** [comment]
Released, thanks for the notice.
