### ISSUE TITLE
[emerg] 1#1: mkdir() "/var/run/openresty/nginx-client-body" failed 

### ISSUE THREAD

**Issue by kaizen-c** [openresty/docker-openresty#251]
When running openresty:1.25.3.1-3-jammy in kubernetes cluster you get below error. 

`` [emerg] 1#1: mkdir() "/var/run/openresty/nginx-client-body" failed (13: Permission denied) ``

Is this a regression as in #124 ?

**Comment by neomantra** [comment]
There no longer is a `VOLUME` directive in the Dockerfiles (see #128), so it is probably not that.   Are you bind-mounting a volume to `/var/run/openresty`?

**Comment by kaizen-c** [comment]
Hey @neomantra i think i did a misconfiguration from my side.
