### ISSUE TITLE
Need to update docker images to 1.25.3.2 with security fixes.

### ISSUE THREAD

**Issue by xiaocang** [openresty/docker-openresty#256]
For details, see https://openresty.org/en/ann-1025003002.html

**Comment by neomantra** [comment]
@xiaocang I'm working on this... seems that Alpine `aarch64`  images are missing:

https://openresty.org/package/alpine/v3.18/main/aarch64/

**Comment by neomantra** [comment]
You can see the failed build in the matrix here:
https://app.travis-ci.com/github/openresty/docker-openresty/builds/271534446

**Comment by xiaocang** [comment]
Thanks for reporting the problem, I'll give it feedback to @agentzh to fix this missing

**Comment by xiaocang** [comment]
Hi @neomantra, the missing Alpine packages have been added.

**Comment by neomantra** [comment]
I've pushed repo tag `1.25.3.2-0` which is now building images with that tag.

https://app.travis-ci.com/github/openresty/docker-openresty/builds/271553952
