### ISSUE TITLE
Openresty:1.21.4.4 Docker image 

### ISSUE THREAD

**Issue by dubloom** [openresty/docker-openresty#258]
Hi there !

There is a docker image for each 1.21.4.x version except the latest one (1.21.4.4). Is there a reason for it ?

Thank you in advance.

**Comment by neomantra** [comment]
The reason would be that I missed its release.  Thanks for the report and I'll make a release for it soon (today/tomorrow).

NB: I see also a 1.19.9.2 release.  I may release that too, it's a lower priority though.   And we'll be having 1.27 released one of these day...

**Comment by Schweinepriester** [comment]
Hello there!

Arrived here also searching for that `1.21.4.4` image… 0:-)

**Comment by neomantra** [comment]
Hello, I started working on this.  Sorry for the tardiness.  Unfortunately it seems that many upstream `1.21.4.4` binaries are missing from OpenResty, so I'm working with them to fix that.    I might make an interim release without many of the upstream flavors.

**Comment by neomantra** [comment]
I upgraded to `1.21.4.4` and [backported several other changes](https://github.com/openresty/docker-openresty/blob/b1.21.4/CHANGELOG.md#12144-0-2024-10-17).  Images are released as `1.21.4.4-0`

https://hub.docker.com/repository/docker/openresty/openresty/tags?name=1.21.4.4-0

Thanks for your patience.
