### ISSUE TITLE
Need to add tzdata package to alpine images

### ISSUE THREAD

**Issue by Pyr0Texn1c** [openresty/docker-openresty#263]
Please add tzdata package to alpine images to make it possible to setup container timezone in offline environments (with no Internet connection)

**Comment by neomantra** [comment]
Thanks for pointing this out -- I see that Debian flavors have this so it makes sense to include it in Alpine. 

```
$ docker run -it --entrypoint=/bin/bash openresty/openresty:1.25.3.2-bookworm -c 'dpkg -l | grep tz'
ii  tzdata                  2024a-0+deb12u1       all          time zone and daylight-saving time data
```

**Comment by neomantra** [comment]
Added this to `1.2.4.4` and will be in forthcoming `1.25.3.2-1`.
