### ISSUE TITLE
Openresty 1.27 support

### ISSUE THREAD

**Issue by rhuddleston** [openresty/docker-openresty#264]
Can we get update Dockerfile for 1.27 that includes openssl 3 and PCRE 10.42?

thanks!

**Comment by neomantra** [comment]
I was staging this this weekend -- it appears that all the upstream build artifacts are now ready so I'll release this today, thanks!

**Comment by neomantra** [comment]
Anybody can check out the changes here on the `b1.27.1` branch:

 * https://github.com/openresty/docker-openresty/commits/b1.27.1
