### ISSUE TITLE
relative paths in a lua block don't seem to work in a docker container

### ISSUE THREAD

**Issue by davidnorthetal** [openresty/docker-openresty#28]
I'm using a short nginx.conf with an init_by_lua_block that opens a file and reads it whole like this:
`fh = io.open("./app/allowed_users.json", "r")`
however, while the path definitely exists relative to the nginx.conf opening the file always fails. ( fh will be null )

The file itself has 644 permission and is owned by root/root.

However, if I do the same thing on a local openresty on the host (no docker), the exact same nginx.conf and path-layout works fine and the file (w/ relative path) is read successfully.

Only if I change the path to an absolute one does it work in the docker container, but I'm trying to a void this.

Any pointers would be greatly appreciated.

**Comment by neomantra** [comment]
The docker-openresty Dockerfile does not declare a `WORKDIR` and neither do the base images they derive from.   So, the default working directory is `/`.  [The nginx Docker images did not set the `WORKDIR`, so I didn't for OpenResty's.]

Nginx has a concept of "prefix" directory which OpenResty defaults to ` /usr/local/openresty/ `.  This is the default place where config files and other nginx-oriented paths are seached.   However, this is not the current working directory.  

`io.open` is a general Lua facility and doesn't consider the "prefix" directory.  

I think you could do this though:
```
fh = io.open(ngx.config.prefix() .. "/app/allowed_users.json", "r")
```

Regarding it working without Docker, whatever is launching it must be setting the working directory.  Are you launching it yourself from that directory perhaps?

**Comment by neomantra** [comment]
Correction to above... OpenResty's nginx prefix is `/usr/local/openresty/nginx/`

**Comment by neomantra** [comment]
Closing because of no follow-up.  Feel free to re-open if there is still an issue.
