### ISSUE TITLE
openresty not using mime.types

### ISSUE THREAD

**Issue by benconnito** [openresty/docker-openresty#29]
nginx docker images work correctly...files loaded from fs are mapped via `conf/mime.types`. however, with openresty i have to add `include /usr/local/openresty/nginx/conf/mime.types;` to get auto type mapping.

**Comment by neomantra** [comment]
OpenResty's default prefix is `/usr/local/openresty/`, so I think you could just `include nginx/conf/mime.types;`? 

I think the nginx images work because they populate `/etc/nginx` with defaults?  I'm wondering if this is just an OpenResty thing, versus the Docker images?

**Comment by agentzh** [comment]
@neomantra No, the nginx prefix of OpenResty is `/usr/local/openresty/nginx/`, which is different from OpenResty's own configure prefix as a whole.

**Comment by neomantra** [comment]
Oh, my bad.  Just corrected the misinformation in #28 .    

Is that claim about `/etc/nginx` correct, i.e. that @benconnito shouldn't expect automatic mapping?

**Comment by agentzh** [comment]
No automatic mapping is provided unless the `mime.types` file is included in the `nginx.conf` main configuration file.

**Comment by agentzh** [comment]
This is standard nginx behavior.

**Comment by benconnito** [comment]
@agentzh so, if this is standard nginx behavior thats fine. my question came about because nginx:1-alpine (https://hub.docker.com/_/nginx/) seems to use it automatically...

**Comment by agentzh** [comment]
@benconnito Nginx's docker image may have special tweaks at compilation time or in its default `nginx.conf` file. Not sure. I'm talking about the default behavior of the official nginx source releases.

**Comment by neomantra** [comment]
Yes, I think he might be using their default `nginx.conf` which basically sets up a simple webserver.  

I didn't do anything like that for OpenResty -- we decided that if somebody wanted that use case they could just use Nginx.   People using OpenResty will be generally making their own `nginx.conf`.

Closing this -- if you think something is actually wrong, feel free to reopen with a test case.  Thanks.

**Comment by benconnito** [comment]
yep, i was doing it in a conf.d file....so it was using the default nginx.conf
