### ISSUE TITLE
include init script

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#3]
@agentzh said there should be an init script.   Is the idea to control the start/stop of the container?  Or of the nginx service inside it.  In other words, are you expecting this init script to be run inside or outside the container by the machine host?

**Comment by agentzh** [comment]
@neomantra I know very little about docker, to be honest. I was thinking along the line of traditional binary rpm/deb packages for Linux, for example.

**Comment by pataquets** [comment]
As per Docker convention, the Nginx process should be end the one running with pid 1 inside the container.
A script can be added if there is the need to replace environments vars inside conf files, create or run botstrapping steps, but not more. After doing the init setup, the script should exec to Nginx to leave it as pid 1.
Maybe initially just building a compile image is enough and leave some time to early users to use it, and in the end an acceptable initscript PR will come, if any is needed. Start small. And leave this ticket open to keep discussion rolling :)

**Comment by neomantra** [comment]
We are going with an ENTRYPOINT command with `-g "daemon off;"`   So lifetime is managed outside of docker.  See #7 and #8.
