### ISSUE TITLE
SSL cert expired for ftp.csx.cam.ac.uk

### ISSUE THREAD

**Issue by bittopaz** [openresty/docker-openresty#30]
Building docker image from Dockerfile would fail due to SSL cert for https://ftp.csx.cam.ac.uk is expired.

Maybe we can use the url below: https://ftp.pcre.org/pub/pcre/

Refer to [this](http://www.pcre.org) for details.

**Comment by neomantra** [comment]
Thanks for bringing that to my attention.  In Chrome I am seeing `NET::ERR_CERT_WAK_SIGNATURE_ALGORITHM`.  I will change to that.
