### ISSUE TITLE
Installing lua-cjson via luarocks failed after switching to the 1.11.2.3-xenial

### ISSUE THREAD

**Issue by lujiajing1126** [openresty/docker-openresty#34]
I use `luarocks` to install `lua-cjson`

the compilation failed with the latest version `1.11.2.3-xenial`

However, with the version `1.11.2.2-xenial`, it worked

```
lua_cjson.c:1298:13: error: static declaration of `luaL_setfuncs` follows non-static declaration
...
```

**Comment by neomantra** [comment]
This is an issue with `lua-cjson`.   Note that [OpenResty 1.11.2.3](http://openresty.org/en/changelog-1011002.html) includes a newer lua-cjson than before (`2.1.0.5`) with the required fixes.

The following links describe the issue and the fix.  If you really want to use that rock instead of the bundled `lua-cjson`, you'll need to apply this change:
 * https://github.com/openresty/lua-cjson/issues/21
 * https://github.com/openresty/lua-cjson/commit/55d22ef3bc5f512a9dadd84fd85895824dad73d9

**Comment by neomantra** [comment]
I successfully installed `lapis` using the following Dockerfile.  I worked around the `lua-cjson` issue by installing the dependencies manually, except `lua-cjson`, and then installing `lapis` with `--deps-mode=none`.

```
FROM openresty/openresty:1.11.2.5-xenial
MAINTAINER "Evan Wies <evan@neomantra.net>"

# install Lapis
RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libssl-dev \
    && /usr/local/openresty/luajit/bin/luarocks install ansicolors \
	&& /usr/local/openresty/luajit/bin/luarocks install date \
	&& /usr/local/openresty/luajit/bin/luarocks install etlua \
	&& /usr/local/openresty/luajit/bin/luarocks install loadkit \
	&& /usr/local/openresty/luajit/bin/luarocks install lpeg \
	&& /usr/local/openresty/luajit/bin/luarocks install luaossl \
	&& /usr/local/openresty/luajit/bin/luarocks install luafilesystem \
	&& /usr/local/openresty/luajit/bin/luarocks install luasocket \
	&& /usr/local/openresty/luajit/bin/luarocks install mimetypes \
	&& /usr/local/openresty/luajit/bin/luarocks install pgmoon \
	&& /usr/local/openresty/luajit/bin/luarocks install --deps-mode=none lapis \
    && DEBIAN_FRONTEND=noninteractive apt-get remove --purge -y \
    	libssl-dev \
    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
 ```

**Comment by neomantra** [comment]
I have noted ways to work around this `lua-cjson` rock issue for `lapis` here:
https://github.com/leafo/lapis/issues/539
