### ISSUE TITLE
Installing luasec with luarockt fails

### ISSUE THREAD

**Issue by hartfordfive** [openresty/docker-openresty#36]
I've attempted to install luasec, as I have some code that does HTTPS requests and requires TLS, therefore I've attempted to install luasec in my docker image by running this:

```
RUN /usr/local/openresty/luajit/bin/luarocks install luasec
```

Although I end up getting this error:

```
Step 7/13 : RUN /usr/local/openresty/luajit/bin/luarocks install luasec
 ---> Running in 054990a68d2a
Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/luasec-0.6-1.rockspec...

Error: Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
Using https://luarocks.org/luasec-0.6-1.rockspec... switching to 'build' mode
The command '/bin/sh -c /usr/local/openresty/luajit/bin/luarocks install luasec' returned a non-zero code: 1
```

I've attempted do download the the *openssl-1.0.2f* manually, extract it to the `/usr/local/openssl` dir and run it with `luarocks install luasec OPENSSL_DIR=/usr/local` although I end up getting other errors saying other files are now missing. 

TO give you some context, here is my Dockerfile:

```
FROM openresty/openresty:alpine-fat

RUN apk add --no-cache git

RUN /usr/local/openresty/luajit/bin/luarocks install md5 
RUN /usr/local/openresty/luajit/bin/luarocks install luasocket

RUN cd /tmp \
        && curl -fSL https://www.openssl.org/source/openssl-1.0.2f.tar.gz -o openssl-1.0.2f.tar.gz \
        && tar xzf openssl-1.0.2f.tar.gz \
        && mkdir -p /usr/include/openssl \
        && cp -R openssl-1.0.2f/ssl/* /usr/include/openssl \
        && cp -R openssl-1.0.2f/crypto/* /usr/include/openssl \
        && cp -R openssl-1.0.2f/*.h /usr/include/openssl \
        && rm -rf openssl-1.0.2f/

RUN /usr/local/openresty/luajit/bin/luarocks install luasec OPENSSL_INCDIR=/usr/include
```

Any ideas how I can get around this issue?

**Comment by agentzh** [comment]
@hartfordfive Careful. The luasec library will always block openresty's event loop and ruin your server performance unless it explicitly makes use of OpenResty's cosocket API (which I doubt).

**Comment by agentzh** [comment]
@hartfordfive Also, openresty already links to an openssl library. If you link to a different version of openssl in some 3rd-party Lua modules, then you are just asking for trouble.

**Comment by neomantra** [comment]
@hartfordfive Some things I note from this.  Since I use `ARG` instead of `ENV` for `RESTY_OPENSSL_VERSION` and other build-time variables.  The "pro" of this is that the environment isn't polluted with that.  The "con" of that is that it is not available to downstream images such as yours.   It is also not available in `docker inspect`, although the Docker Hub build logs show it.  But I see how this could be useful, so I'm going to make a separate issue with respect to this.

I started mucking with this a bit and I think your problem is that you aren't installing OpenSSL properly -- you are just coping files wholesale, which perhaps not what the actual installer does?  The error I am seeing is:
```
/usr/include/openssl/ssl.h:149:28: fatal error: openssl/comp.h: No such file or directory
```
But through the way you are manually installing it, that file is being stored at `/usr/local/include/openssl/comp/comp.h`.

So if you really want to do this, despite agentzh's warning (which are important), you need to properly install `openssl`.

**Comment by hartfordfive** [comment]
@agentzh @neomantra Thanks for the feedback.  I had a feeling I was probably doing something I shouldn't.  I've switched over from **socket.http** to **[resty.http](https://luarocks.org/modules/pintsized/lua-resty-http)** to perform my HTTP calls and it's working fine.  The issue is that I also have to issue some HTTPS POST requests to perform and I was using the **ssl.https** library for that. With it, I could specify the following parameters to the http client:
```
  key = "/etc/certs/ssl/client.key";
  certificate = "/etc/certs/ssl/client.crt";
  cafile = "/etc/certs/ssl/server.chain";
```
Although it doesn't seem like I can specify those with the `resty.http` client.  Any suggestions on what I can do to solve this issue?  Thanks again for the help.

**Comment by agentzh** [comment]
@hartfordfive James Hurst's lua-resty-http library does support SSL: https://github.com/pintsized/lua-resty-http And it's nonblocking. If you use a library on luarocks that do not explicitly mention support for OpenResty, then it will almost always block the nginx event loop miserably.

**Comment by agentzh** [comment]
@hartfordfive This is why we maintain our own Lua library repository for OpenResty, called OPM:

http://opm.openresty.org/

**Comment by neomantra** [comment]
Closing -- feel free to reopen if there is still something to review w.r.t. this Docker tooling.

**Comment by doktoroblivion** [comment]
@agentzh @hartfordfive  Have either of you successfully actually gotten lua-resty-http to work with HTTPS using cert/key/ca with a secret?  If so, would really like to know how, this does not appear to work, at least not from the documentation that is provided and I even went through Hurst's code!  I get
```
2018/02/26 19:50:27 [debug] 21#0: *3 [lua] analytics_access.lua:109: **** Connect with TLS ****
2018/02/26 19:50:27 [debug] 21#0: *3 [lua] analytics_access.lua:114: Connected 1
2018/02/26 19:50:27 [debug] 21#0: *3 [lua] analytics_access.lua:116: **** handshake ****
2018/02/26 19:50:27 [error] 21#0: *3 SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40
```
