### ISSUE TITLE
Make envsubst available in the images

### ISSUE THREAD

**Issue by eemeli** [openresty/docker-openresty#38]
The official [nginx image](https://hub.docker.com/_/nginx/) includes the `envsubst` command in the final image, and even refers to it in the documentation as a workaround for using environment variables in nginx configuration.

Is there a reason why it's not included in the Openresty images (admittedly I've only checked `jessie`, which is missing the `gettext-base` package) and/or is there an alternative for using environment variables for Openresty configuration?

**Comment by neomantra** [comment]
This seems to not be an nginx feature, and thus not an OpenResty feature, but rather something Nginx explicitly adds to their Docker tooling.   

It's not clear to me how important this is for OpenResty.  If one needs to access the environment, they can do so with Lua.  Plain OpenResty can't do this.   Also there are other ways in which nginx files can be made dynamically, such as `envconsul`.

It is easy enough for us to add, and perhaps we should for some parity with the Nginx images.  We can also do their lightweight `envsubst` install trick for alpine.   It does add 1MB to the image.

Whatever we do should be across all the images, except perhaps the `alpine` image.

**Comment by eemeli** [comment]
For an example use case, [this](https://github.com/worldcon75/api/blob/978085c8124947f7343e301a00becbf374d495ec/nginx/Dockerfile) is our Dockerfile using `openresty:jessie` as a base, which installs & uses `envsubst` to read the env vars declared as build args in [this](https://github.com/worldcon75/api/blob/978085c8124947f7343e301a00becbf374d495ec/docker-compose.override.yml) docker-compose config file.

If there's an alternative/better way e.g. using Lua for setting the server name & SSL file paths, I'd be interested to hear about it.

**Comment by neomantra** [comment]
It looks like you cannot set those without modifying the file (although there is some fancy SSL manipulation that can be done with `ngx.ssl`).

Since the Nginx image have `envsubst` and it only adds 0.2MB to `stretch` and 4MB to `centos-rpm` and 1MB on `alpine-fat`, I've added support in all images except `alpine`.  See commit 64186bff511fde4734ebbe7e8cea92e468e7107c
