### ISSUE TITLE
make available on Docker Hub

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#4]
We should make this available on Docker Hub.   Then people can do `docker pull openresty/docker-openresty`

@agentzh said that he would give @neomantra access to the `openresty` username on Docker Hub.  openresty`.  That can happen in private -- this ticket just reminds us to do it :)

**Comment by JanJakes** [comment]
Any updates on this issue?

**Comment by agentzh** [comment]
@JanJakes Alas. I still cannot receive the password reset email from DockerHub. Very strange.

**Comment by neomantra** [comment]
I could make them available on my Docker hub account, but I think the openresty account is a better spot.

**Comment by JanJakes** [comment]
What about trying to contact somebody from Docker Hub or something? It's been blocked by the password for almost a month now :)

**Comment by agentzh** [comment]
BTW, the `openresty` account is not in my possession. I could only register `openrestyorg`. If you think `openrestyorg` is good enough, then I'll contact DockerHub's customer service or something like that.

**Comment by pataquets** [comment]
@neomantra: Instead of ```openresty/docker-openresty``` as stated in the original post, I would remove the ```docker-``` part, sinc it's kind of implied/redundant.
@agentzh: if you haven't done it yet, say so and I'll ping Hub's cust service to try at least to ask them to make the owner of the account aware of this issue.

**Comment by agentzh** [comment]
@pataquets I haven't yet. Feel free to go ahead :) Thanks a lot!

**Comment by pataquets** [comment]
Done. I contacted DH support asking for help and linked them here.

**Comment by agentzh** [comment]
@pataquets Thanks!

**Comment by pataquets** [comment]
The openresty user has been deemed abandoned by DH support and, after converting it to an org, he support staff made me the owner of it.
Who shall I transfer the org ownership to?

**Comment by agentzh** [comment]
@pataquets Wow. This is really awesome! I hope that you can transfer the ownership to admin@openresty.org and then I'll share it with the rest of the OpenResty team. Thank you very much!

**Comment by agentzh** [comment]
@pataquets The DockerHub ID associated with `admin@openresty.org` is `openrestyadmin`.

**Comment by pataquets** [comment]
Done. Let me know when I can leave the owners group safely.

**Comment by agentzh** [comment]
@pataquets You can stay there if you wish :) I can confirm that it works now. @neomantra Please send me your DH account or email privately.

**Comment by neomantra** [comment]
Images are now available at Docker Hub at https://hub.docker.com/r/openresty/openresty/ under the following tags:
 * latest-trusty
 * latest-xenial
 * latest-centos
 * latest-alpine

Try `docker pull openresty/openresty:latest-alpine`

**Comment by agentzh** [comment]
@neomantra Thanks for your work!

**Comment by pataquets** [comment]
Congrats and thanks for your work, guys!

**Comment by pataquets** [comment]
@agentzh: Honored to stay in the DH org :)

**Comment by agentzh** [comment]
@pataquets We won't have that account without your help ;) Thanks a lot!
