### ISSUE TITLE
Add image to official repository

### ISSUE THREAD

**Issue by amingilani** [openresty/docker-openresty#46]
This may a slightly more involved process, but have you considered contributing this image to the docker [official images](https://hub.docker.com/explore/) repository?

I was personally surprised at having to use `openresty/openresty` and I'm sure a lot of people are too.

The official builds are tracked at [docker-library/official-images](https://github.com/docker-library/official-images) and the README file has instructions on how to propose adding the image.

**Comment by neomantra** [comment]
At first I thought it was too immature for it, but now with the official packaging method it could be  interesting.  

I myself don't have time for the endeavor and don't mind the extra `openresty/` -- in the end it is just a base image for private/local repositories.

**Comment by amingilani** [comment]
I think I can help out. Would you like me to create the relevant pull requests?

**Comment by neomantra** [comment]
Sure, it says `help wanted`.   I'm not against this being in the official repos, and we can still maintain something separate here if we want to diverge from their requirements.

I'm not totally sure how it works for the official packaging, but I think it should be based on the OpenResty packaging, perhaps on `stretch` Dockerfile?   `nginx` Dockerfiles are Debian based and point to `nginx.org` 's .deb repo, , so it's probably fine to point to  OpenResty's.

**Comment by neomantra** [comment]
Closing as stale
