### ISSUE TITLE
Luarocks Missing in Stretch

### ISSUE THREAD

**Issue by amingilani** [openresty/docker-openresty#47]
Here's what I get when my build tries to install the uuid rock

```
Step 2/6 : RUN /usr/local/openresty/luajit/bin/luarocks install uuid
 ---> Running in 24a96b5a9f67
/bin/sh: 1: /usr/local/openresty/luajit/bin/luarocks: not found
```

I don't think Luarocks is included in stretch, even though the documentation says it's only unavailable in alpine:

>LuaRocks is included in the alpine-fat, centos, centos-rpm, trusty, and xenial variants. It is excluded from alpine because it generally requires a build system and we want to keep that variant lean.

**Comment by amingilani** [comment]
Here's the base image declaration: `FROM openresty/openresty:1.11.2.4-stretch`

**Comment by amingilani** [comment]
accidentally closed it

**Comment by neomantra** [comment]
See further down in the documentation. It references this file:
https://github.com/openresty/docker-openresty/blob/master/stretch/Dockerfile.luarocks_example

It does so for the same reason - if you are installing a package you are deriving a Dockerfile so keep unnecessary things from the main Dockerfile. 

I do think the flow of the docs need to be updated a bit.
