### ISSUE TITLE
Alpine image is broken

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#5]
From a comment from vus520 on Docker Hub:

```
1.9.7.4-alpine, (alpine/Dockerfile)

Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/openresty/luajit/lib/libluajit-5.1.so.2)
Error relocating /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: _Unwind_SetIP: symbol not found
Error relocating /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: _Unwind_GetCFA: symbol not found
Error relocating /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: _Unwind_DeleteException: symbol not found
Error relocating /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: _Unwind_SetGR: symbol not found
Error relocating /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: _Unwind_RaiseException: symbol not found
```

Although he didn't leave much other info, I guess LuaJIT has a dependency on gcc's runtime library.  So the cleanup phase of the docker image build process needs to be adjusted.

**Comment by ruslantalpa** [comment]
I think this is worth investigating more
You might get away with adding this as runtime dependency http://pkgs.alpinelinux.org/package/v3.4/main/armhf/libgcc and not the whole gcc

after this change, the image is 165M size and that defeats the purpose of using alpine as base
`openresty/openresty   alpine              3b4c539c6ec2        32 hours ago        165.6 MB`

looking into it, i'll post back if this works

**Comment by neomantra** [comment]
I am actually in progress with exactly that (using `libgcc`), after thinking about our other issue/conversation ;)

**Comment by neomantra** [comment]
If you are interested in following along:
```
diff --git a/alpine/Dockerfile b/alpine/Dockerfile
index 2a110b0..1036f52 100644
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -55,21 +55,21 @@ RUN \
     apk add --no-cache --virtual .build-deps \
         build-base \
         curl \
+        gcc \
         gd-dev \
         geoip-dev \
         libxslt-dev \
         linux-headers \
         make \
         perl-dev \
+        readline \
         zlib-dev \
     && apk add --no-cache \
-        gcc \
         gd \
         geoip \
+        libgcc \
         libxslt \
         ncurses \
-        perl \
-        readline \
         zlib \
     && cd /tmp \
     && curl -fSL https://www.openssl.org/source/openssl-${RESTY_OPENSSL_VERSION}.tar.gz -o openssl-${RESTY_OPENSSL_VERSION}.tar.gz \
```

**Comment by ruslantalpa** [comment]
I can confirm using libgcc instead of gcc works.
I checked it like this:
1) compiled with libgcc instead of gcc
2) checked the image size (87M)
3) inside the container i executed
`/usr/local/openresty/bin/resty -e "ngx.say('hello')"` and it worked
4) removed the lib like this `mv /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so.1.temp` and checked step 3 again, and it generated the reported error

long story short, change this line https://github.com/openresty/docker-openresty/blob/master/alpine/Dockerfile#L66

from `gcc \` to `libgcc \`

PS: it's worth investigating a bit where these 87M come from
alpine is about 5M
/usr/local/openresty after the build is 32.4M

so there are an additional ~40M that might not be really needed

**Comment by ruslantalpa** [comment]
you don't need gcc in .build-deps, it compiles without it

**Comment by ruslantalpa** [comment]
curious as to why you chose to add `--with-http_perl_module=dynamic` since the point of openresty is to use lua. Will anybody be using perl with this image?

**Comment by ruslantalpa** [comment]
removing perl get's us to 
`openresty             latest              f2e26742a6bb        37 seconds ago      45.96 MB`

It's worth looking at this image https://github.com/ficusio/openresty/blob/master/alpine/Dockerfile since it's size 13M and see why this official image is so big

**Comment by neomantra** [comment]
So you are right on a few fronts... 
* `libgcc` can be used instead of `gcc` as a runtime depend
* `gcc` is included in `build-base` so adding it is redundant
* why include the perl module (I was following an amalgamation of various nginx guides)

I'll wait a bit to see if you have more comments, but otherwise I'll commit these changes.

Thanks for looking into this.

**Comment by ruslantalpa** [comment]
looks like the docs are a bit old, downloading that image shows this
`ficusio/openresty     latest              849eac5fefd4        4 months ago        35.03 MB`

**Comment by ruslantalpa** [comment]
I have not discovered any other 'pearls' so i guess you should commit this and get the image to 80M.
The next step would be to decide on perl/resty issue.

PS: I realise that i't mostly "a thing in my head" but it bugs me a bit that the OS is 5M and this image is 80M :). For now, 80M is good enough for me to go on with my project and if along the way i find some other optimisations, i'll post back.

Thank you

**Comment by neomantra** [comment]
I just pushed that gcc changeset and it should be on Docker Hub in a bit.
