### ISSUE TITLE
Docker 1.11.2.5 build failures

### ISSUE THREAD

**Issue by jbyers** [openresty/docker-openresty#50]
A cross-section of the 1.11.2.5 builds failed:

  https://hub.docker.com/r/openresty/openresty/builds/

The failures don't have a pattern I can see; alpine worked, alpine-fat failed; centos worked, centos-rpm failed. Can they be retried?

**Comment by neomantra** [comment]
Thanks for pointing that out.  I will look at why I didn't get (or missed) the build failures.  I fixed the issue and pushed.  I'll close this ones the new builds are complete.
