### ISSUE TITLE
1.13.6.1 docker images

### ISSUE THREAD

**Issue by tirumaraiselvan** [openresty/docker-openresty#57]
Hi

Wondering when the latest release (1.13.6.1) pre-built docker images will be put on docker hub?

Thanks!

**Comment by neomantra** [comment]
I'll be doing this over this weekend.  Sorry I've not had the cycles to do it sooner.

**Comment by neomantra** [comment]
These have been tagged and building for a while.  Will close this once they are done.

**Comment by neomantra** [comment]
OK, these are up at the `1.13.6.1-<distro>` tags.   Note that the version-unspecified tags (e.g. `<distro>` are currently behind this because of build system issues.
