### ISSUE TITLE
expire, ttl not are nill, version is the neweast

### ISSUE THREAD

**Issue by goodje** [openresty/docker-openresty#63]
when I call expire/ttl on shared memory, it says `'attempt to call method 'ttl' (a nil value)'`, but I saw the arguments in the compilation params, there is `nginx version: openresty/1.13.6.1
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
built with OpenSSL 1.0.2k  26 Jan 2017
...
--add-module=../ngx_lua-0.10.11
...`.
the instruction from Dockerfile: `FROM openresty/openresty:xenial`

sorce code:
`local memory = ngx.shared.waf
local restraint = "127.0.0.1"

memory:incr(restraint, 1, 0) -- incr request times: ip, step, initial value
memory:ttl(restraint)
memory:expire(restraint, expire_time)
`

**Comment by neomantra** [comment]
This is working for me:
```
docker run openresty/openresty:xenial /usr/local/openresty/bin/resty --shdict="waf 1m" -e 'require "resty.core.shdict" ; local memory = ngx.shared.waf ; local restraint = "127.0.0.1" ; memory:ttl(restraint)'
```

I don't think your issue has anything to do with the docker image... two things I'm doing there that aren't explicit in what you wrote:
 1) creating the `--shdict`
 2) requiring `resty.core.shdict` (or `resty.core`)

**Comment by goodje** [comment]
oh, my bad, it became working after I added "require resty.core.shdict".

based on the document, I was thinking that it was needed that `resty.core.shdict` or `resty.core` to be required but not be inputted as `require resty.core.shdict or resty.core`, and my openresty/lua_ngx_module might have been incorrect.

thanks @neomantra
