### ISSUE TITLE
Problem with default conf

### ISSUE THREAD

**Issue by axelssonHakan** [openresty/docker-openresty#64]
Is the COPY command for nginx.conf working for the docker?

If I `docker exec` into the container the file `/usr/local/openresty/nginx/conf/nginx.conf` it's
the default config.

Not sure what's the working directory for the Docker build but the nginx.conf is in ../nginx.conf. Should the COPY command be `COPY ../nginx.conf /usr/local/openresty/nginx/conf/nginx.conf`?

What else could cause my conf to be the default and not conatining the include state `include /etc/nginx/conf.d/*.conf;`

https://github.com/openresty/docker-openresty/blob/99acf4aa92a3150a454feec67e626bb0ab4f7e2b/alpine/Dockerfile#L96

**Comment by axelssonHakan** [comment]
https://hub.docker.com/r/openresty/openresty/builds/bgdcda7qz7yrvvfyokpj2p4/

Build failed: COPY failed: stat /var/lib/docker/tmp/docker-builder338523020/nginx.conf: no such file or directory

**Comment by axelssonHakan** [comment]
And some more info :-)

The @1.13.6.1 doesn't seem to overwrite the conf. So the documentation refers to a version that hasn't been released, or?

https://github.com/openresty/docker-openresty/blob/1.13.6.1/alpine/Dockerfile

**Comment by neomantra** [comment]
Those are not tagged with 1.13.6.1. You have to use the untagged images which are at master. 

See the bottom of #40

If you go to that 1.13.6.1 git tag, you will see the correct docs.

I haven’t received big reports related to master so I probably will retag that soon. 

Note that master uses OpenResty v1.13.6.1

**Comment by zabio3** [comment]
Where are you working in the directory?

```
$ pwd
~/docker-openresty
$ docker build -t myopenresty -f alpine/Dockerfile .
```

Unfortunately, (for practical and security reasons I guess), if you want to add/copy local content, it must be located under the same root path than the Dockerfile.

https://stackoverflow.com/questions/24537340/docker-adding-a-file-from-a-parent-directory

**Comment by neomantra** [comment]
Correct, these images must be built from the root directory.  Prior to #40 you could build from the "flavor"'s directory because nothing was COPYied.   This also broke Docker's automated build as noted in that issue because it changes the working directory to that of the Dockerfile.

**Comment by neomantra** [comment]
I think this is taken care of with the latest releases.
