### ISSUE TITLE
Unknown directive "more_set_headers"

### ISSUE THREAD

**Issue by serain** [openresty/docker-openresty#69]
I'm using the docker image:
```
FROM openresty/openresty:1.13.6.1-0-alpine

```

My configuration looks like this:
```
        location ~ contentlength$ {
            # testing
            more_set_headers "Content-Length: 999";
        }
```

Error:
```
nginx_1   | nginx: [emerg] unknown directive "more_set_headers" in /etc/nginx/nginx.conf:28
```

According to the [documentation](https://github.com/openresty/headers-more-nginx-module):
```
Also, this module is included and enabled by default in the OpenResty bundle.
```

Is there anything I'm missing?

**Comment by neomantra** [comment]
I’m AFK today but try using the `stretch` Image which uses the official OpenResty packages.  

The alpine images are more intended for advanced / customized / streamlined use.

**Comment by neomantra** [comment]
I have updated the documentation to point people to the upstream images.
