### ISSUE TITLE
No way to make openresty run as PID1

### ISSUE THREAD

**Issue by cpoole** [openresty/docker-openresty#7]
When running the image with the command given in the readme:
`docker run [options] openresty/openresty:latest-trusty /usr/local/openresty/nginx/sbin/nginx`
The image immediately exits.

If I start the container in an interactive bash shell and then call nginx my pstree looks as follows:
```
root@f4dbc6cba0ca:/# pstree -npcUa
bash,1
  ├─nginx,73
  │   └─nginx,74                
  └─pstree,81 -npcUa
```
This is to be expected, one master and one worker process. What doesn't make sense is why this process can't be run as PID1

I have tested this on docker 1.11 and 1.12 beta and both have the same behavior

**Comment by neomantra** [comment]
A quick solution for you is probably to pass `-g "daemon off;"` to nginx.  See http://stackoverflow.com/questions/18861300/how-to-run-nginx-within-a-docker-container-without-halting

This should be in this repo's README and I should also make a Dockerfile `ENTRYPOINT` with this like other nginx docker repos.

**Comment by neomantra** [comment]
Oh, you can also put that in your nginx config file.

**Comment by cpoole** [comment]
Fantastic @neomantra. Thanks so much for the quick response. I simply passed that in as part of the CMD.

**Comment by neomantra** [comment]
Happy to help.   I am re-opening because I think the README and Dockerfile should be updated.  Will close when that is done.

**Comment by cpoole** [comment]
What is your thought on updating the dockerfile? Are you thinking adding a CMD to each dockerfile or are you thinking about adding an entrypoint script that runs `/usr/local/openresty/nginx/sbin/nginx -g "daemon off;"`

**Comment by neomantra** [comment]
I was thinking about adding this to all the Dockerfiles.
```
ENTRYPOINT ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
```

and then one could do this:
```
docker run -v /my/path:/resty openresty/openresty:latest-trusty -p /resty
```

and if they wanted something else they could specify an alternate entry point:
```
docker run --entrypoint /usr/local/openresty/bin/resty -v /my/path:/resty /resty/myscript.lua
```

**Comment by cpoole** [comment]
sounds good to me, i prefer an entyrpoint to this instead of a CMD. I submitted a pull request

**Comment by neomantra** [comment]
Your ENTRYPOINT changeset has been merged, closing this issuing.
