### ISSUE TITLE
 module not found

### ISSUE THREAD

**Issue by ilkosta** [openresty/docker-openresty#71]
Hi,

trying to run the default openresty/openresty:jessie container I some the errors:

module ngx_http_lua_cache_module.so not found, than 
`
lualib/user_code/hooks.lua:6: module 'subzero.jwt_session_cookie' not found
`

some hints?

**Comment by neomantra** [comment]
Can you try using the `stretch` image?  It is built from upstream OpenResty packages and should have more complete support and less surprises. 

I’m actually in the midst of archiving many of the image flavors and `jessie` is going away.

**Comment by ilkosta** [comment]
Thanks, don't worked, but I think the problem is inside a modified nginx.conf responsible of the loading of modules.
I will open the ticket in the corresponding project. 
Thanks for the hints.
