### ISSUE TITLE
Unable to find ngx_http_image_filter_module.so

### ISSUE THREAD

**Issue by edrw-bt** [openresty/docker-openresty#72]
Our new openresty containers built from the latest docker image that use the image filter module have been failing to start with this error:

```
nginx: [emerg] dlopen() "/usr/local/openresty/nginx/modules/ngx_http_image_filter_module.so" failed (/usr/local/openresty/nginx/modules/ngx_http_image_filter_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/conf.d/nginx.conf:1
```
It appears that the modules directory is no longer in the container
```
$ docker run -it openresty/openresty:centos-rpm bash
[root@14cd5f07befa /]# ls /usr/local/openresty/nginx/
conf  html  logs  sbin  tapset
```

Was this intentional? If so what is the best way to install dynamic modules?

**Comment by neomantra** [comment]
I have not intentionally been removing anything, but I *did* just (like yesterday and today) update the images to OpenResty 1.13.6.2.    Can you be explicit about the image tag/id you are using?

**Comment by edrw-bt** [comment]
We've been going off the latest centos tag with no version. `FROM openresty/openresty:centos`

**Comment by neomantra** [comment]
OK, so you will want to change that to be: `openresty/openresty:1.13.6.1-2-centos` to avoid breakage.

I archived the "centos" Dockerfile and now only build centos from the upstream OpenResty packages.  I renamed "centos-rpm" to "centos".   See the [`CHANGELOG`](https://github.com/openresty/docker-openresty/blob/master/CHANGELOG.md).

It seems that the upstream RPM version does not have that module directory (even in 1.13.6.1 versions).   I don't have time to investigate that right right now, but wanted to get you the right tag ASAP to get you back on your feet.

**Comment by edrw-bt** [comment]
Thanks for the help. I'll continue to dig into it and let you know if I figure anything out.

**Comment by neomantra** [comment]
From a quick look, it seems like the `ngx_http_image_filter_module` is not included in the upstream CentOS packages, whereas it is included as `http_image_filter_module=dynamic` in the `RESTY_CONFIG_OPTIONS` of the source-built Dockerfile.

[I wish the Docker Hub had better analytics so we could see which images are actually most popular!]

**Comment by neomantra** [comment]
This is has the list of included modules in the RPM:
https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec

**Comment by edrw-bt** [comment]
Ok that makes sense. Hadn't touched this part of our codebase in almost a year, was wondering why this was the only container we used the source-built base for - probably for that reason. I preferred the rpm bases for our other openresty containers. 

I am seeing the modules in the `openresty/openresty:1.13.6.1-2-centos` container too so I think we're good now.

```
$ docker run -it openresty/openresty:1.13.6.1-2-centos ls /usr/local/openresty/nginx/modules
ngx_http_geoip_module.so	 ngx_http_xslt_filter_module.so
ngx_http_image_filter_module.so
```

Thanks for the quick help here! I'll go ahead and close this out.

**Comment by agentzh** [comment]
@edrw-bt It makes sense to add all the remaining standard nginx modules as dynamic modules in the official OpenResty binary packages. Will you please submit a pull request for the following repo:

https://github.com/openresty/openresty-packaging/

Many thanks!

**Comment by agentzh** [comment]
@edrw-bt This way you can just use the binary package based docker images instead of the source-built ones ;)

**Comment by edrw-bt** [comment]
Sounds good @agentzh I got some stuff to catch up on today, but I'll try to get that PR in this weekend.

**Comment by agentzh** [comment]
@edrw-bt Great. Thanks!
