### ISSUE TITLE
stream-lua-nginx-module is not compiled into the binary

### ISSUE THREAD

**Issue by ochinchina** [openresty/docker-openresty#85]
When I try to write lua script in the tcp stream, I got error like:

```
2018/11/04 09:54:08 [emerg] 489#489: "content_by_lua_block" directive is not allowed here in /usr/local/openresty/nginx/conf/test.conf:10
nginx: [emerg] "content_by_lua_block" directive is not allowed here in /usr/local/openresty/nginx/conf/test.conf:10
nginx: configuration file /usr/local/openresty/nginx/conf/test.conf test failed

```
and the test.conf is pasted from https://github.com/openresty/stream-lua-nginx-module, its content is:
```
events {
    worker_connections 1024;
}

stream {
    # define a TCP server listening on the port 1234:
    server {
        listen 1234;

        content_by_lua_block {
            ngx.say("Hello, Lua!")
        }
    }
}
```

if there is a plan to compile the stream-lua-nginx-module to the openresty docker image?

**Comment by neomantra** [comment]
Which image tag are you running from?

All of the build-from-source Dockerfiles should have `--with-stream` and `--with-stream_ssl_module`, but maybe something else is missing?   And I would think the upstream OpenResty packages have it?

**Comment by agentzh** [comment]
@neomantra Recent versions of the upstream OpenResty versions enable the stream lua module by default unless getting explicitly turned off in the `./configure` command line.

**Comment by ochinchina** [comment]
> 
> 
> Which image tag are you running from?
> 
> All of the build-from-source Dockerfiles should have `--with-stream` and `--with-stream_ssl_module`, but maybe something else is missing? And I would think the upstream OpenResty packages have it? Have you tried with `centos` or `stretch` images?

openresty/openresty:latest is used, not tried the "centos" or "stretch" image. I will try if the "centos" and "stretch" image has the stream-lua embeded.

**Comment by neomantra** [comment]
Closing since it seems like it is OK.  Feel free to reopen if not.
