### ISSUE TITLE
1.13.6.2 & -1 stretch-fat opm get curl error

### ISSUE THREAD

**Issue by FlameBearer** [openresty/docker-openresty#86]
When building the below Dockerfile getting a curl SSL error.

* Fetching knyar/nginx-lua-prometheus  
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
ERROR: failed to run command "curl -sS -i -A 'opm 0.0.5 (x86_64-linux-gnu-thread-multi, perl v5.24.1)' 'https://opm.openresty.org/api/pkg/fetch?account=knyar&name=nginx-lua-prometheus&op=&version='"
--
FROM openresty/openresty:1.13.6.2-stretch-fat

RUN opm get knyar/nginx-lua-prometheus

EXPOSE 8080
CMD nginx -g 'daemon off;'

**Comment by neomantra** [comment]
I just tried that (manually and with your Dockerfile) and it worked for me.

`opm` downloaded it from here:
https://opm.openresty.org/api/pkg/tarball/knyar/nginx-lua-prometheus-0.20171117.opm.tar.gz

If you pull a fresh image does it work?  The `ca-certificates` package is installed.

**Comment by FlameBearer** [comment]
You're right it worked fine on my personal computer must be an issue with my company's proxy/firewall/vpn.
