### ISSUE TITLE
About nginx.conf

### ISSUE THREAD

**Issue by gavinv587** [openresty/docker-openresty#87]
I found two line about  nginx.conf when build the docker's image by dockerfile of Centos
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf
I am confused , Why there are two ? which one the docker will load?

**Comment by neomantra** [comment]
I see this section is not labeled in the table of contents (right below "Usage"):
https://github.com/openresty/docker-openresty#nginx-config-files

Does that help explain it?

`/usr/local/openresty/nginx/conf/nginx.conf` is loaded by default.  It has a directive `include /etc/nginx/conf.d/*.conf;` which loads any files in that path.  That `nginx.vh.default.conf` is copied in there.   You can override either of them depending on what you are trying to do -- but most cases will overwrite `/etc/nginx/conf.d/` with bind-mounting.

TODOs for this issue:
 * add TOC link to nginx-config-files
 * add descriptions to `nginx.conf` and `nginx.vh.default.conf` so people looking there don't need to jump around

**Comment by gavinv587** [comment]
now,i understand, thanks million

**Comment by neomantra** [comment]
Reopening this to track that I need to update the docs -- thanks!
