### ISSUE TITLE
Consider installing unzip for luarocks

### ISSUE THREAD

**Issue by FourierTransformer** [openresty/docker-openresty#9]
In latest-centos, you need to install `unzip` to install most luarocks. Perhaps this should be included in the container by default.

**Comment by codeb2cc** [comment]
Don't forget `centos-rpm`.

**Comment by neomantra** [comment]
@codeb2cc I just added it.   I also bumped the RESTY_RPM_VERSION because the previous one was no longer in the yum repos.  It should be on the Docker Hub in an hour or so.
