### ISSUE TITLE
can I get real client ip in docker-openresty?

### ISSUE THREAD

**Issue by zffocussss** [openresty/docker-openresty#96]
I am running docker-openresty.but I can only get ip which is docker bridge ip.How can I get real client IP.

Below is the request flow.
client-->LB-->docker-nginx-->docker-openresty

**Comment by neomantra** [comment]
Do you mean the IP is the Docker bridge itself or on the bridge’s network?  From your diagram, I would think the client IP would be that of the docker-nginx (which is proxying).

You need to be sure the proxies are forwarding that information and read it from the header.  For example:

 https://stackoverflow.com/questions/42140346/get-client-ip-address-with-nginx-lua

**Comment by neomantra** [comment]
Closing as stale
